---
name: compilation_manifest
director_uuid: REPLACEME
release:
  name: cloud-foundry
  version: 122.1-dev
compilation:
  workers: 1
  reuse_compilation_vms: true
  network: default
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 4
update:
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 2
networks:
- name: default
  subnets:
  - reserved:
    - 10.150.0.2-10.150.88.2
    - 10.150.88.201-10.150.255.254
    static:
    - 10.150.88.3-10.150.88.125
    range: 10.150.0.0/16
    gateway: 10.150.0.1
    dns:
    - 10.0.0.130
    - 8.8.8.8
    - 192.168.1.130
    cloud_properties:
      name: VM Network
resource_pools:
- name: windows
  network: default
  size: 0
  stemcell:
    name: uhuru-windows-2008R2
    version: 0.9.3
  cloud_properties:
    ram: 2048
    disk: 10000
    cpu: 4
  env:
    windows:
      product_key: 2J2XH-YDM37-8YFR3-W866C-RK4PV
- name: sqlserver
  network: default
  size: 0
  stemcell:
    name: uhuru-windows-2008R2-sqlserver
    version: 0.9.4
  cloud_properties:
    ram: 2048
    disk: 10000
    cpu: 4
  env:
    windows:
      product_key: 2J2XH-YDM37-8YFR3-W866C-RK4PV
- name: tiny
  network: default
  size: 0
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties:
    ram: 300
    disk: 5000
    cpu: 1
- name: small
  network: default
  size: 1
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties:
    ram: 512
    disk: 5000
    cpu: 1
- name: medium
  network: default
  size: 0
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties:
    ram: 1024
    disk: 5000
    cpu: 2
- name: large
  network: default
  size: 0
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties:
    ram: 2048
    disk: 10000
    cpu: 4
- name: deas
  network: default
  size: 0
  stemcell:
    name: bosh-stemcell-php
    version: 0.6.4.3
  cloud_properties:
    ram: 1024
    disk: 5000
    cpu: 2
jobs:
- name: debian_nfs_server
  template: debian_nfs_server
  instances: 1
  resource_pool: small
  persistent_disk: 50000
  networks:
  - name: default
- name: syslog_aggregator
  template: syslog_aggregator
  instances: 0
  resource_pool: medium
  persistent_disk: 1000
  networks:
  - name: default
    static_ips: []

- name: nats
  template: nats
  instances: 0
  resource_pool: small
  networks:
  - name: default
    static_ips: []

- name: hbase_master
  template: hbase_master
  instances: 0
  resource_pool: medium
  persistent_disk: 2048
  networks:
  - name: default
    static_ips: []

- name: hbase_slave
  template: hbase_slave
  instances: 0
  resource_pool: medium
  persistent_disk: 2048
  networks:
  - name: default
    static_ips: []

- name: opentsdb
  template: opentsdb
  instances: 0
  resource_pool: medium
  persistent_disk: 16384
  networks:
  - name: default
    static_ips: []

- name: collector
  template: collector
  instances: 0
  resource_pool: medium
  networks:
  - name: default
- name: dashboard
  template: dashboard
  instances: 0
  resource_pool: medium
  networks:
  - name: default
- name: ccdb
  template: postgres
  instances: 0
  resource_pool: medium
  persistent_disk: 10000
  networks:
  - name: default
    static_ips: []

  properties:
    db: ccdb
- name: uaadb
  template: postgres
  instances: 0
  resource_pool: small
  persistent_disk: 1000
  networks:
  - name: default
    static_ips: []

  properties:
    db: uaadb
- name: vcap_redis
  template: vcap_redis
  instances: 0
  resource_pool: medium
  persistent_disk: 5000
  networks:
  - name: default
    static_ips: []

- name: uaa
  template: uaa
  instances: 0
  resource_pool: small
  networks:
  - name: default
- name: cloud_controller
  template: cloud_controller
  instances: 0
  resource_pool: medium
  networks:
  - name: default
- name: stager
  template: stager
  instances: 0
  resource_pool: medium
  networks:
  - name: default
- name: router
  template: router
  instances: 0
  resource_pool: medium
  networks:
  - name: default
    default:
    - dns
    - gateway
    static_ips: []

- name: health_manager
  template: health_manager
  instances: 0
  resource_pool: small
  networks:
  - name: default
- name: dea
  template: dea
  instances: 0
  resource_pool: deas
  networks:
  - name: default
- name: mysql_node
  template: mysql_node
  instances: 0
  resource_pool: medium
  persistent_disk: 75000
  networks:
  - name: default
    static_ips: []

- name: mongodb_node
  template: mongodb_node
  instances: 0
  resource_pool: medium
  persistent_disk: 75000
  networks:
  - name: default
    static_ips: []

- name: mongodb_gateway
  template: mongodb_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: redis_node
  template: redis_node
  instances: 0
  resource_pool: large
  persistent_disk: 10240
  networks:
  - name: default
    static_ips: []

- name: redis_gateway
  template: redis_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: mysql_gateway
  template: mysql_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: rabbit_node
  template: rabbit_node
  instances: 0
  resource_pool: medium
  persistent_disk: 10240
  networks:
  - name: default
    static_ips: []

- name: rabbit_gateway
  template: rabbit_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: postgresql_node
  template: postgresql_node
  instances: 0
  resource_pool: medium
  persistent_disk: 75000
  networks:
  - name: default
    static_ips: []

- name: postgresql_gateway
  template: postgresql_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: simple_webui
  template: simple_webui
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
    static_ips: []

- name: mssql_gateway
  template: mssql_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: uhurufs_gateway
  template: uhurufs_gateway
  instances: 0
  resource_pool: tiny
  networks:
  - name: default
- name: win_dea
  template: win_dea
  instances: 0
  resource_pool: windows
  networks:
  - name: default
- name: uhuru_tunnel
  template: uhuru_tunnel
  instances: 0
  resource_pool: windows
  networks:
  - name: default
- name: uhurufs_node
  template: uhurufs_node
  instances: 0
  persistent_disk: 75000
  resource_pool: windows
  networks:
  - name: default
    static_ips: []

- name: mssql_node
  template: mssql_node
  instances: 0
  persistent_disk: 75000
  resource_pool: sqlserver
  networks:
  - name: default
    static_ips: []

properties:
  domain: testcfm.com
  description: Cloud application platform
  support_address: http://support.mitza.me
  env: {}

  networks:
    apps: default
    management: default
  uhuru:
    simple_webui:
      port: 9191
      cloud_name: Uhuru Cloud
      cloud_admin_download_url: http://www.uhurucloud.com/tools/cloudadmin
      visual_studio_plugin_download_url: http://www.uhurucloud.com/tools/visualstudio
      vmc_url: http://docs.cloudfoundry.com/tools/vmc/installing-vmc.html
      eclipse_url: http://docs.cloudfoundry.com/tools/STS/configuring-STS.html
      signup_message: Host your web applications in minutes. We support apps written in PHP, Node.js, Ruby, Java and .NET.
      copyright_message: Copyright Uhuru Software 2012
      welcome_message: Welcome to your PAAS cloud
      color_theme: Simple
      recaptcha_public_key: <enter your recaptcha public key>
      recaptcha_private_key: <enter your recaptcha private key>
      activation_link_secret: m8oS8D1Jvw8K
      admin_email: dev@uhurusoftware.com
      admin_password: password1234!
      default_random_password: 4vahbPnVn2Bj
      logging_level: debug
      email:
        from: uhuru@uhurusoftware.com
        from_alias: Uhuru Cloud
        server: smtp.domain.com
        port: "587"
        user: user
        secret: ""
        auth_method: ":plain"
        enable_tls: false
      contact:
        company: Company INC.
        address: Address of company
        phone: "1234567890"
        email: uhuru@uhurusoftware.com
  win_dea:
    filerport: 12346
    statusport: 12345
    max_memory: 6144
  uhurufs_gateway:
    check_orphan_interval: 7200
    token: "0xfeedface"
    service_timeout: 60
    node_timeout: 30
    supported_versions:
    - "0.9"
    version_aliases:
      current: "0.9"
  uhurufs_node:
    capacity: 200
    statusport: 12345
    default_version: 0.9
  mssql_gateway:
    check_orphan_interval: 7200
    token: "0xfeedface"
    service_timeout: 60
    node_timeout: 30
    supported_versions:
    - "2008"
    version_aliases:
      current: "2008"
  mssql_node:
    capacity: 200
    admin_user: sa
    admin_password: changem3!
    port: 1433
    max_db_size: 20
    max_long_query: 3
    max_long_tx: 30
    max_user_conns: 20
    default_version: 2008
    statusport: 12345
    product_key: gyf3t-h2v88-grpph-hwrjp-qrtyb
  nats:
    user: 2fe5c7da4ecff9ddc155381a761e401a
    password: 0008422158c208f774c9c86d88364f4b
    address: 10.150.88.5
    port: 4222
  ccdb:
    user: root
    password: 97deb454f32ebe3a583aa59f8cab9a68
    address: 10.150.88.6
    port: 5432
    pool_size: 10
    dbname: ce69a33ecdc86b8f417bc72f7a9bf9c2
    databases:
    - tag: cc
      name: ce69a33ecdc86b8f417bc72f7a9bf9c2
    roles:
    - tag: admin
      name: root
      password: 97deb454f32ebe3a583aa59f8cab9a68
  cc:
    srv_api_uri: api.testcfm.com
    password: 3dd08ca30e901ab7aefb49ff44fd163d
    token: 1cafa56659fc3fc4613ed9babe82b70c
    use_nginx: true
    new_stager_percent: 100
    staging_upload_user: db225ce2ec6ed41d3a4783403af16dab
    staging_upload_password: 72a25dda6ea505cdaf78fc29260d14d4
    allow_registration: false
    allow_external_app_uris: true
    bootstrap_users:
    - email: dev@uhurusoftware.com
      password: password1234!
      is_admin: true
      is_hashed_password: false
    admins:
    - dev@uhurusoftware.com
    default_account_capacity:
      memory: "512"
      app_uris: 8
      services: "4"
      apps: 4
  vcap_redis:
    address: 10.150.88.8
    port: 5454
    password: 744adddba29ad33345b35dbee4695b03
    maxmemory: 1024
  router:
    client_inactivity_timeout: 120
    app_inactivity_timeout: 120
    status:
      port: 8080
      user: 73b24dd74cc2baf233ed42b7cc8679fa
      password: c0fb3255a0704e92809272321df29119
    redirect_parent_domain_to: www.testcfm.com
  dashboard:
    uaa:
      client_id: dashboard
      client_secret: secret
  dea:
    max_memory: 6144
    maxmemory: 1024
  nfs_server:
    address: 10.150.88.3
    network: 10.150.0.0/16
  hbase_master:
    address:
    hbase_master:
      port: 60000
      webui_port: 60010
      heap_size: 768
    hbase_zookeeper:
      heap_size: 768
    hadoop_namenode:
      port: 9000
  hbase_slave:
    hbase_regionserver:
      port: 60020
      heap_size: 768
    addresses:
    -
  opentsdb:
    address:
    port: 4242
  service_plans:
    mysql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: false
          capacity: 100
          max_db_size: 30
          max_long_query: 20
          max_long_tx: 0
          max_clients: 20
    postgresql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: false
          capacity: 100
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 30
          max_clients: 20
    mongodb:
      free:
        job_management:
          high_water: 3000
          low_water: 100
        configuration:
          allow_over_provisioning: false
          capacity: 50
          quota_files: 4
          max_clients: 500
    redis:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: false
          capacity: 50
          max_memory: 16
          max_swap: 32
          max_clients: 500
    rabbit:
      free:
        job_management:
          low_water: 100
          high_water: 1400
        configuration:
          allow_over_provisioning: false
          max_memory_factor: 0.5
          max_clients: 512
          capacity: 50
    mssql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: false
          capacity: 100
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 0
          max_clients: 20
          lifecycle:
            enable: true
            worker_count: 1
            snapshot:
              quota: 10
    uhurufs:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: false
          capacity: 200
          max_memory: 16
          max_swap: 32
          max_clients: 500
  mysql_gateway:
    supported_versions:
    - "5.1"
    version_aliases:
      current: "5.1"
    check_orphan_interval: 7200
    token: Alg82gD2mXjtyq5B
    node_timeout: 60
    service_timeout: 30
  mysql_node:
    supported_versions:
    - "5.1"
    default_versions: "5.1"
    production: true
    password: aaa13djkas
    op_time_limit: 50
  redis_gateway:
    supported_versions:
    - "2.2"
    version_aliases:
      current: "2.2"
    token: gQ1mjpqdzhljRGju
    check_orphan_interval: 7200
    node_timeout: 60
    service_timeout: 30
  redis_node:
    supported_versions:
    - "2.2"
    default_versions: "2.2"
    op_time_limit: 50
  mongodb_gateway:
    supported_versions:
    - "1.8"
    - "2.0"
    version_aliases:
      current: "2.0"
      deprecated: "1.8"
    check_orphan_interval: 7200
    token: ELcjgTsd7Tsfpcnz
    node_timeout: 60
    service_timeout: 30
  mongodb_node:
    supported_versions:
    - "1.8"
    - "2.0"
    default_version: "1.8"
    op_time_limit: 50
  rabbit_gateway:
    supported_versions:
    - "2.4"
    version_aliases:
      current: "2.4"
    check_orphan_interval: 7200
    token: 9rxCftgnofi0GXZ6
    node_timeout: 60
    service_timeout: 30
  rabbit_node:
    supported_versions:
    - "2.4"
    default_versions: "2.4"
    op_time_limit: 50
  postgresql_gateway:
    check_orphan_interval: 7200
    token: L01xwjdGIhHH0I4L
    supported_versions:
    - "9.0"
    version_aliases:
      current: "9.0"
  postgresql_node:
    production: true
    supported_versions:
    - "9.0"
    default_version: "9.0"
  syslog_aggregator:
    address: 10.150.88.4
    port: 54321
  report_processor:
    syslog_aggregator:
      address: 10.150.0.153
      port: 54321
  stager:
    max_staging_duration: 600
    max_active_tasks: 10
    queues:
    - staging
  uaadb:
    address: 10.150.0.159
    port: 2544
    roles:
    - tag: admin
      name: root
      password: OPSLMp7nrq7g
    databases:
    - tag: uaa
      name: uaa
  uaa:
    cc:
      token_secret: 77c951a462dcd78fd5d0ef55ed2a853e
      client_secret: 78d9b9197058e324b712a811d5f8530f
    admin:
      client_secret: 85b0685f1940790ac410c9e54c3de49a
    login:
      client_secret: 8c86c82f9ec84a61221a36f71427e840
    clients:
      dashboard:
        id: dashboard
        secret: cbe8ed72209ca361e670768dd8194f13
        authorized-grant-types: authorization_code,refresh_token
        scope: openid,dashboard.user
        authorities: uaa.resource,tokens.read,tokens.write
        access-token-validity: 5000
      dashborad_admin:
        id: dashboard_admin
        secret: somesecret
        authorized-grant-types: client_credentials
        scope: uaa.none
        authorities: scim.read,scim.write,tokens.read,tokens.write,clients.read,clients.write,uaa.admin
        access-token-validity: 5000
    scim:
      users:
      - admin|eRihCu1V|admin@uhurucloud.net|Dash|Board|openid,dashboard.user
