#!/bin/bash

function get_yaml()
{
# gets a value from a yaml document
cat <<EOF | ruby
require 'yaml'
f = "$appdir/$1/manifest.yml"
log = File.open( f )
yp = YAML::load_documents( log ) { |doc|
  puts "#{doc['applications']['.']['runtime']}"
}
EOF
}

function get_yaml1()
{
# gets an app's framework from the yml file
cat <<EOF | ruby
require 'yaml'
f = "$appdir/$1/manifest.yml"
log = File.open( f )
yp = YAML::load_documents( log ) { |doc|
  puts "#{doc['applications']['.']['framework']['name']}"
}
EOF
}

function trim()
{
  echo $*|tr -d ' '
  #sed 's/^ *//g'
}

function random_string()
{
  cat /dev/urandom|tr -dc "A-Za-z0-9"|fold -w $1|head -n 1
}

function random_hex_string()
{
  cat /dev/urandom|tr -dc "a-f0-9"|fold -w $1|head -n 1
}

function random_guid()
{
  echo "`random_hex_string 8`-`random_hex_string 4`-`random_hex_string 4`-`random_hex_string 4`-`random_hex_string 12`"
}

function validate_ip()
{
  local ret=1

  case "$*" in
    ""|*[!0-9.]*|*[!0-9]) return 1 ;;
  esac

  local IFS=.
  set -- $*

  [ $# -eq 4 ] && [ ${1:-300} -le 255 ] && [ ${2:-300} -le 255 ] && [ ${3:-300} -le 255 ] && [ ${4:-300} -le 255 ] && ret=0

  [ $ret -ne 0 ] && msgbox "Invalid IP" "This is not a valid IP address."

  return $ret
}

function validate_subnet()
{
  local ret=1

  case "$*" in
    ""|*[!0-9.]*|*[!0-9]) return 1 ;;
  esac

  local IFS=.
  set -- $*

  [ $# -eq 4 ] && [ ${1:-300} -le 255 ] && [ ${2:-300} -le 255 ] && [ ${3:-300} -le 255 ] && [ ${4:-300} -eq 0 ] && ret=0

  [ $ret -ne 0 ] && msgbox "Invalid subnet" "Please enter a subnet which ends with '.0'"

  return $ret
}

function add_to_ip()
{
  local add=$2 IFS=.
  set -- $1
  echo "$1.$2.$3.$(( $4 + $add ))"
}

function infobox()
{
  local msg title
  [ $# -eq 1 ] &&
    {
    title="Information"
    msg=$1
    } ||
    {
    title=$1
    msg=$2
    }

  $dialog --backtitle "$bgtitle" --title " $title " --infobox "\n${msg}\n\n" 0 0
}

function yesno()
{
  local msg title
  [ $# -eq 1 ] &&
    {
    title="Question"
    msg=$1
    } ||
    {
    title=$1
    msg=$2
    }

  $dialog --backtitle "$bgtitle" --title " $title " --yesno "\n${msg}\n\n" 0 0
}

function msgbox()
{
  local msg title
  [ $# -eq 1 ] &&
    {
    title="Message"
    msg=$1
    } ||
    {
    title=$1
    msg=$2
    }

  $dialog --backtitle "$bgtitle" --title " $title " --msgbox "\n${msg}\n\n" 0 0
}

function textbox()
{
  lines=`tput lines`
  cols=`tput cols`

  $dialog --backtitle "$bgtitle" --title " $1 " --textbox $2 $(( $lines - 4 )) $(( $cols - 6 ))
}

function inputbox()
{
  local msg title default
  [ $# -eq 1 ] &&
    {
    title="Input text"
    msg=$1
    default=""
    } ||
    {
    title=$1
    msg=$2
    default=$3
    }

  $dialog --backtitle "$bgtitle" --title " $title " --inputbox "\n${msg}\n\n" 0 0 $default 2>$tmpdir/input.out
}

function passwordbox()
{
  local pass

  $dialog --backtitle "$bgtitle" --title " $1 " --insecure --passwordbox "\nPlease enter password\n\n" 0 0 2>$tmpdir/password.out &&
    {
    pass=`cat $tmpdir/password.out`
    $dialog --backtitle "$bgtitle" --title " $1 " --insecure --passwordbox "\nEnter password again\n\n" 0 0 2>$tmpdir/password.out

    [ "`cat $tmpdir/password.out`" != "$pass" ] &&
      {
      msgbox "The passwords dont match"
      return 1
      } ||
      {
      return 0
      }
    } || return 1
}

function edit_file()
{
  $dialog --backtitle "$bgtitle" \
  --ok-label "Save" \
  --title " Edit `basename $1` " \
  --editbox $1 0 0 \
  2>$tmpdir/edit.out && cp -f $tmpdir/edit.out $1

  rm -f $tmpdir/edit.out
}

function cleanup()
{
  rm -rf $tmpdir
}

function write_vars_doubled()
{
local conffile=$1
echo "conf_bosh_reserved_start=$conf_bosh_reserved_start" >$conffile
echo "conf_bosh_reserved_stop=$conf_bosh_reserved_stop" >>$conffile
echo "conf_bosh_static_start=$conf_bosh_static_start" >>$conffile
echo "conf_bosh_static_stop=$conf_bosh_static_stop" >>$conffile
echo "conf_bosh_range=$conf_bosh_range" >>$conffile
echo "conf_network_gateway=$conf_network_gateway" >>$conffile
echo "conf_network_dns1=$conf_network_dns1" >>$conffile
echo "conf_network_dns2=$conf_network_dns2" >>$conffile
echo "conf_cloud_name=\"$conf_cloud_name\"" >>$conffile
echo "bosh_pool_small_size=$bosh_pool_small_size" >>$conffile
echo "bosh_pool_small_ram=$bosh_pool_small_ram" >>$conffile
echo "bosh_pool_small_disk=$bosh_pool_small_disk" >>$conffile
echo "bosh_pool_small_cpu=$bosh_pool_small_cpu" >>$conffile
echo "bosh_pool_medium_size=$bosh_pool_medium_size" >>$conffile
echo "bosh_pool_medium_ram=$bosh_pool_medium_ram" >>$conffile
echo "bosh_pool_medium_disk=$bosh_pool_medium_disk" >>$conffile
echo "bosh_pool_medium_cpu=$bosh_pool_medium_cpu" >>$conffile
echo "bosh_pool_large_size=$bosh_pool_large_size" >>$conffile
echo "bosh_pool_large_ram=$bosh_pool_large_ram" >>$conffile
echo "bosh_pool_large_disk=$bosh_pool_large_disk" >>$conffile
echo "bosh_pool_large_cpu=$bosh_pool_large_cpu" >>$conffile
echo "conf_bosh_nats_ip=$conf_bosh_nats_ip" >>$conffile
echo "conf_bosh_postgres_ip=$conf_bosh_postgres_ip" >>$conffile
echo "conf_bosh_redis_ip=$conf_bosh_redis_ip" >>$conffile
echo "conf_bosh_director_ip=$conf_bosh_director_ip" >>$conffile
echo "conf_bosh_blobstore_ip=$conf_bosh_blobstore_ip" >>$conffile
echo "conf_bosh_blobstore_ip=$conf_bosh_blobstore_ip" >>$conffile
echo "conf_bosh_nats_ip=$conf_bosh_nats_ip" >>$conffile
echo "conf_bosh_postgres_ip=$conf_bosh_postgres_ip" >>$conffile
echo "conf_bosh_redis_ip=$conf_bosh_redis_ip" >>$conffile
echo "conf_bosh_director_ip=$conf_bosh_director_ip" >>$conffile
echo "conf_vcenter_host=$conf_vcenter_host" >>$conffile
echo "conf_vcenter_user=$conf_vcenter_user" >>$conffile
echo "conf_vcenter_password=$conf_vcenter_password" >>$conffile
echo "conf_datacenter_name=$conf_datacenter_name" >>$conffile
echo "conf_datacenter_vmfolder=$conf_datacenter_vmfolder" >>$conffile
echo "conf_datacenter_templatefolder=$conf_datacenter_templatefolder" >>$conffile
echo "conf_datacenter_micro_diskpath=$conf_datacenter_micro_diskpath" >>$conffile
echo "conf_datacenter_deployer_diskpath=$conf_datacenter_deployer_diskpath" >>$conffile
echo "conf_datacenter_bosh_diskpath=$conf_datacenter_bosh_diskpath" >>$conffile
echo "conf_datacenter_datastorepattern=$conf_datacenter_datastorepattern" >>$conffile
echo "conf_datacenter_persistentpattern=$conf_datacenter_persistentpattern" >>$conffile
echo "conf_bosh_mixeddatastores=$conf_bosh_mixeddatastores" >>$conffile
echo "conf_vcenter_clustername=$conf_vcenter_clustername" >>$conffile
echo "cloudfoundry_compilation_ram=$cloudfoundry_compilation_ram" >>$conffile
echo "cloudfoundry_compilation_disk=$cloudfoundry_compilation_disk" >>$conffile
echo "cloudfoundry_compilation_cpu=$cloudfoundry_compilation_cpu" >>$conffile
echo "conf_bosh_reserved_start=$conf_bosh_reserved_start" >>$conffile
echo "conf_bosh_reserved_stop=$conf_bosh_reserved_stop" >>$conffile
echo "conf_bosh_static_start=$conf_bosh_static_start" >>$conffile
echo "conf_bosh_static_stop=$conf_bosh_static_stop" >>$conffile
echo "conf_bosh_range=$conf_bosh_range" >>$conffile
echo "conf_network_gateway=$conf_network_gateway" >>$conffile
echo "conf_network_dns1=$conf_network_dns1" >>$conffile
echo "conf_network_dns2=$conf_network_dns2" >>$conffile
echo "conf_cloud_name=\"$conf_cloud_name\"" >>$conffile
echo "cloudfoundry_pool_tiny_size=$cloudfoundry_pool_tiny_size" >>$conffile
echo "cloudfoundry_pool_tiny_ram=$cloudfoundry_pool_tiny_ram" >>$conffile
echo "cloudfoundry_pool_tiny_disk=$cloudfoundry_pool_tiny_disk" >>$conffile
echo "cloudfoundry_pool_tiny_cpu=$cloudfoundry_pool_tiny_cpu" >>$conffile
echo "cloudfoundry_pool_tiny_password=$cloudfoundry_pool_tiny_password" >>$conffile
echo "cloudfoundry_pool_small_size=$cloudfoundry_pool_small_size" >>$conffile
echo "cloudfoundry_pool_small_ram=$cloudfoundry_pool_small_ram" >>$conffile
echo "cloudfoundry_pool_small_disk=$cloudfoundry_pool_small_disk" >>$conffile
echo "cloudfoundry_pool_small_cpu=$cloudfoundry_pool_small_cpu" >>$conffile
echo "cloudfoundry_pool_small_password=$cloudfoundry_pool_small_password" >>$conffile
echo "cloudfoundry_pool_medium_size=$cloudfoundry_pool_medium_size" >>$conffile
echo "cloudfoundry_pool_medium_ram=$cloudfoundry_pool_medium_ram" >>$conffile
echo "cloudfoundry_pool_medium_disk=$cloudfoundry_pool_medium_disk" >>$conffile
echo "cloudfoundry_pool_medium_cpu=$cloudfoundry_pool_medium_cpu" >>$conffile
echo "cloudfoundry_pool_medium_password=$cloudfoundry_pool_medium_password" >>$conffile
echo "cloudfoundry_pool_large_size=$cloudfoundry_pool_large_size" >>$conffile
echo "cloudfoundry_pool_large_ram=$cloudfoundry_pool_large_ram" >>$conffile
echo "cloudfoundry_pool_large_disk=$cloudfoundry_pool_large_disk" >>$conffile
echo "cloudfoundry_pool_large_cpu=$cloudfoundry_pool_large_cpu" >>$conffile
echo "cloudfoundry_pool_large_password=$cloudfoundry_pool_large_password" >>$conffile
echo "cloudfoundry_deas_count=$cloudfoundry_deas_count" >>$conffile
echo "cloudfoundry_pool_deas_ram=$cloudfoundry_pool_deas_ram" >>$conffile
echo "cloudfoundry_pool_deas_disk=$cloudfoundry_pool_deas_disk" >>$conffile
echo "cloudfoundry_pool_deas_cpu=$cloudfoundry_pool_deas_cpu" >>$conffile
echo "cloudfoundry_pool_deas_password=$cloudfoundry_pool_deas_password" >>$conffile
echo "cloudfoundry_ip_debian_nfs_server=$cloudfoundry_ip_debian_nfs_server" >>$conffile
echo "cloudfoundry_ip_syslog_aggregator=$cloudfoundry_ip_syslog_aggregator" >>$conffile
echo "cloudfoundry_ip_nats=$cloudfoundry_ip_nats" >>$conffile
echo "cloudfoundry_ip_hbase_master=$cloudfoundry_ip_hbase_master" >>$conffile
echo "cloudfoundry_ip_hbase_slave=$cloudfoundry_ip_hbase_slave" >>$conffile
echo "cloudfoundry_ip_router=$cloudfoundry_ip_router" >>$conffile
echo "cloudfoundry_ip_opentsdb=$cloudfoundry_ip_opentsdb" >>$conffile
echo "cloudfoundry_ip_ccdb_postgres=$cloudfoundry_ip_ccdb_postgres" >>$conffile
echo "cloudfoundry_ip_uaadb=$cloudfoundry_ip_uaadb" >>$conffile
echo "cloudfoundry_ip_vcap_redis=$cloudfoundry_ip_vcap_redis" >>$conffile
echo "cloudfoundry_cloud_controller_count=$cloudfoundry_cloud_controller_count" >>$conffile
echo "cloudfoundry_stager_count=$cloudfoundry_stager_count" >>$conffile
echo "cloudfoundry_router_count=$cloudfoundry_router_count" >>$conffile
echo "cloudfoundry_deas_count=$cloudfoundry_deas_count" >>$conffile
echo "cloudfoundry_mysqlnode_count=$cloudfoundry_mysqlnode_count" >>$conffile
echo "cloudfoundry_mongodbnode_count=$cloudfoundry_mongodbnode_count" >>$conffile
echo "cloudfoundry_redisnode_count=$cloudfoundry_redisnode_count" >>$conffile
echo "cloudfoundry_rabbitnode_count=$cloudfoundry_rabbitnode_count" >>$conffile
echo "cloudfoundry_uhurufsnode_count=$cloudfoundry_uhurufsnode_count" >>$conffile
echo "cloudfoundry_postgresqlnode_count=$cloudfoundry_postgresqlnode_count" >>$conffile
echo "cloudfoundry_mssqlnode_count=$cloudfoundry_mssqlnode_count" >>$conffile
echo "cloudfoundry_windea_count=$cloudfoundry_windea_count" >>$conffile
echo "cloudfoundry_domain=$cloudfoundry_domain" >>$conffile
echo "cloudfoundry_nats_username=$cloudfoundry_nats_username" >>$conffile
echo "cloudfoundry_nats_password=$cloudfoundry_nats_password" >>$conffile
echo "cloudfoundry_ip_nats=$cloudfoundry_ip_nats" >>$conffile
echo "cloudfoundry_ccdb_password=$cloudfoundry_ccdb_password" >>$conffile
echo "cloudfoundry_ip_ccdb_postgres=$cloudfoundry_ip_ccdb_postgres" >>$conffile
echo "cloudfoundry_ccdb_dbname=$cloudfoundry_ccdb_dbname" >>$conffile
echo "cloudfoundry_ccdb_ccname=$cloudfoundry_ccdb_ccname" >>$conffile
echo "cloudfoundry_ccdb_roles_password=$cloudfoundry_ccdb_roles_password" >>$conffile
echo "cloudfoundry_srv_api_uri=$cloudfoundry_srv_api_uri" >>$conffile
echo "cloudfoundry_cc_password=$cloudfoundry_cc_password" >>$conffile
echo "cloudfoundry_cc_token=$cloudfoundry_cc_token" >>$conffile
echo "cloudfoundry_cc_staging_upload_user=$cloudfoundry_cc_staging_upload_user" >>$conffile
echo "cloudfoundry_cc_staging_upload_password=$cloudfoundry_cc_staging_upload_password" >>$conffile
echo "cloudfoundry_cc_admin=$cloudfoundry_cc_admin" >>$conffile
echo "cloudfoundry_ip_vcap_redis=$cloudfoundry_ip_vcap_redis" >>$conffile
echo "cloudfoundry_vcap_redis_password=$cloudfoundry_vcap_redis_password" >>$conffile
echo "cloudfoundry_vcap_redis_maxmemory=$cloudfoundry_vcap_redis_maxmemory" >>$conffile
echo "cloudfoundry_router_username=$cloudfoundry_router_username" >>$conffile
echo "cloudfoundry_router_password=$cloudfoundry_router_password" >>$conffile
echo "cloudfoundry_dea_maxmemory=$cloudfoundry_dea_maxmemory" >>$conffile
echo "cloudfoundry_ip_debian_nfs_server=$cloudfoundry_ip_debian_nfs_server" >>$conffile
echo "conf_bosh_range=$conf_bosh_range" >>$conffile
echo "cloudfoundry_ip_hbase_master=$cloudfoundry_ip_hbase_master" >>$conffile
echo "cloudfoundry_ip_hbase_slave=$cloudfoundry_ip_hbase_slave" >>$conffile
echo "cloudfoundry_ip_opentsdb=$cloudfoundry_ip_opentsdb" >>$conffile
echo "cloudfoundry_mysql_gateway_token=$cloudfoundry_mysql_gateway_token" >>$conffile
echo "cloudfoundry_mssql_gateway_token=$cloudfoundry_mssql_gateway_token" >>$conffile
echo "cloudfoundry_uhurufs_gateway_token=$cloudfoundry_uhurufs_gateway_token" >>$conffile
echo "cloudfoundry_redis_gateway_token=$cloudfoundry_redis_gateway_token" >>$conffile
echo "cloudfoundry_mongodb_gateway_token=$cloudfoundry_mongodb_gateway_token" >>$conffile
echo "cloudfoundry_rabbit_gateway_token=$cloudfoundry_rabbit_gateway_token" >>$conffile
echo "cloudfoundry_postgresql_gateway_token=$cloudfoundry_postgresql_gateway_token" >>$conffile
echo "cloudfoundry_ip_syslog_aggregator=$cloudfoundry_ip_syslog_aggregator" >>$conffile
echo "cloudfoundry_ip_syslog_aggregator=$cloudfoundry_ip_syslog_aggregator" >>$conffile
echo "cloudfoundry_ip_uaadb=$cloudfoundry_ip_uaadb" >>$conffile
echo "cloudfoundry_uaadb_password=$cloudfoundry_uaadb_password" >>$conffile
echo "cloudfoundry_uaa_cc_token_secret=$cloudfoundry_uaa_cc_token_secret" >>$conffile
echo "cloudfoundry_uaa_cc_client_secret=$cloudfoundry_uaa_cc_client_secret" >>$conffile
echo "cloudfoundry_uaa_admin_client_secret=$cloudfoundry_uaa_admin_client_secret" >>$conffile
echo "cloudfoundry_uaa_login_client_secret=$cloudfoundry_uaa_login_client_secret" >>$conffile
echo "cloudfoundry_uaa_dashboard_secret=$cloudfoundry_uaa_dashboard_secret" >>$conffile
echo "cloudfoundry_dash_username=$cloudfoundry_dash_username" >>$conffile
echo "cloudfoundry_dash_password=$cloudfoundry_dash_password" >>$conffile
echo "cloudfoundry_dash_email=$cloudfoundry_dash_email" >>$conffile
echo "conf_network_micro_ip=$conf_network_micro_ip" >>$conffile
echo "conf_network_netmask=$conf_network_netmask" >>$conffile
echo "conf_network_gateway=$conf_network_gateway" >>$conffile
echo "conf_network_dns1=$conf_network_dns1" >>$conffile
echo "conf_network_dns2=$conf_network_dns2" >>$conffile
echo "conf_cloud_name=\"$conf_cloud_name\"" >>$conffile
echo "conf_resources_persistent=$conf_resources_persistent" >>$conffile
echo "conf_resources_ram=$conf_resources_ram" >>$conffile
echo "conf_resources_disk=$conf_resources_disk" >>$conffile
echo "conf_resources_cpu=$conf_resources_cpu" >>$conffile
echo "conf_network_ntp1=$conf_network_ntp1" >>$conffile
echo "conf_network_ntp2=$conf_network_ntp2" >>$conffile
echo "conf_vcenter_host=$conf_vcenter_host" >>$conffile
echo "conf_vcenter_user=$conf_vcenter_user" >>$conffile
echo "conf_vcenter_password=$conf_vcenter_password" >>$conffile
echo "conf_datacenter_name=$conf_datacenter_name" >>$conffile
echo "conf_datacenter_vmfolder=$conf_datacenter_vmfolder" >>$conffile
echo "conf_datacenter_templatefolder=$conf_datacenter_templatefolder" >>$conffile
echo "conf_datacenter_datastorepattern=$conf_datacenter_datastorepattern" >>$conffile
echo "conf_datacenter_persistentpattern=$conf_datacenter_persistentpattern" >>$conffile
echo "conf_datacenter_mixeddatastores=$conf_datacenter_mixeddatastores" >>$conffile
echo "conf_vcenter_clustername=$conf_vcenter_clustername" >>$conffile
echo "conf_network=$conf_network" >>$conffile
echo "version_bosh_cli=$version_bosh_cli" >>$conffile
echo "version_bosh=$version_bosh" >>$conffile
echo "version_cloudfoundry=$version_cloudfoundry" >>$conffile
}

function write_vars()
{
local conffile=$1
cat /dev/null >$conffile
echo "bosh_pool_small_size=$bosh_pool_small_size" >>$conffile
echo "bosh_pool_small_ram=$bosh_pool_small_ram" >>$conffile
echo "bosh_pool_small_disk=$bosh_pool_small_disk" >>$conffile
echo "bosh_pool_small_cpu=$bosh_pool_small_cpu" >>$conffile
echo "bosh_pool_medium_size=$bosh_pool_medium_size" >>$conffile
echo "bosh_pool_medium_extra_size=$bosh_pool_medium_extra_size" >>$conffile
echo "bosh_pool_medium_ram=$bosh_pool_medium_ram" >>$conffile
echo "bosh_pool_medium_disk=$bosh_pool_medium_disk" >>$conffile
echo "bosh_pool_medium_extra_disk=$bosh_pool_medium_extra_disk" >>$conffile
echo "bosh_pool_medium_cpu=$bosh_pool_medium_cpu" >>$conffile
echo "bosh_pool_large_size=$bosh_pool_large_size" >>$conffile
echo "bosh_pool_large_ram=$bosh_pool_large_ram" >>$conffile
echo "bosh_pool_large_disk=$bosh_pool_large_disk" >>$conffile
echo "bosh_pool_large_cpu=$bosh_pool_large_cpu" >>$conffile
echo "conf_bosh_blobstore_ip=$conf_bosh_blobstore_ip" >>$conffile
echo "conf_bosh_nats_ip=$conf_bosh_nats_ip" >>$conffile
echo "conf_bosh_postgres_ip=$conf_bosh_postgres_ip" >>$conffile
echo "conf_bosh_redis_ip=$conf_bosh_redis_ip" >>$conffile
echo "conf_bosh_director_ip=$conf_bosh_director_ip" >>$conffile
echo "conf_datacenter_vmfolder=$conf_datacenter_vmfolder" >>$conffile
echo "conf_datacenter_micro_diskpath=$conf_datacenter_micro_diskpath" >>$conffile
echo "conf_datacenter_deployer_diskpath=$conf_datacenter_deployer_diskpath" >>$conffile
echo "conf_datacenter_bosh_diskpath=$conf_datacenter_bosh_diskpath" >>$conffile
echo "conf_bosh_mixeddatastores=$conf_bosh_mixeddatastores" >>$conffile
echo "cloudfoundry_compilation_ram=$cloudfoundry_compilation_ram" >>$conffile
echo "cloudfoundry_compilation_disk=$cloudfoundry_compilation_disk" >>$conffile
echo "cloudfoundry_compilation_cpu=$cloudfoundry_compilation_cpu" >>$conffile
echo "conf_bosh_reserved_start=$conf_bosh_reserved_start" >>$conffile
echo "conf_bosh_reserved_stop=$conf_bosh_reserved_stop" >>$conffile
echo "conf_bosh_static_start=$conf_bosh_static_start" >>$conffile
echo "conf_bosh_static_stop=$conf_bosh_static_stop" >>$conffile
echo "conf_bosh_range=$conf_bosh_range" >>$conffile
echo "conf_network_gateway=$conf_network_gateway" >>$conffile
echo "conf_network_dns1=$conf_network_dns1" >>$conffile
echo "conf_network_dns2=$conf_network_dns2" >>$conffile
echo "conf_cloud_name=\"$conf_cloud_name\"" >>$conffile
echo "cloudfoundry_pool_tiny_size=$cloudfoundry_pool_tiny_size" >>$conffile
echo "cloudfoundry_pool_tiny_ram=$cloudfoundry_pool_tiny_ram" >>$conffile
echo "cloudfoundry_pool_tiny_disk=$cloudfoundry_pool_tiny_disk" >>$conffile
echo "cloudfoundry_pool_tiny_cpu=$cloudfoundry_pool_tiny_cpu" >>$conffile
echo "cloudfoundry_pool_tiny_password=$cloudfoundry_pool_tiny_password" >>$conffile
echo "cloudfoundry_pool_small_size=$cloudfoundry_pool_small_size" >>$conffile
echo "cloudfoundry_pool_small_ram=$cloudfoundry_pool_small_ram" >>$conffile
echo "cloudfoundry_pool_small_disk=$cloudfoundry_pool_small_disk" >>$conffile
echo "cloudfoundry_pool_small_cpu=$cloudfoundry_pool_small_cpu" >>$conffile
echo "cloudfoundry_pool_small_password=$cloudfoundry_pool_small_password" >>$conffile
echo "cloudfoundry_pool_medium_size=$cloudfoundry_pool_medium_size" >>$conffile
echo "cloudfoundry_pool_medium_ram=$cloudfoundry_pool_medium_ram" >>$conffile
echo "cloudfoundry_pool_medium_disk=$cloudfoundry_pool_medium_disk" >>$conffile
echo "cloudfoundry_pool_medium_cpu=$cloudfoundry_pool_medium_cpu" >>$conffile
echo "cloudfoundry_pool_medium_password=$cloudfoundry_pool_medium_password" >>$conffile
echo "cloudfoundry_pool_large_size=$cloudfoundry_pool_large_size" >>$conffile
echo "cloudfoundry_pool_large_ram=$cloudfoundry_pool_large_ram" >>$conffile
echo "cloudfoundry_pool_large_disk=$cloudfoundry_pool_large_disk" >>$conffile
echo "cloudfoundry_pool_large_cpu=$cloudfoundry_pool_large_cpu" >>$conffile
echo "cloudfoundry_pool_large_password=$cloudfoundry_pool_large_password" >>$conffile
echo "cloudfoundry_pool_deas_ram=$cloudfoundry_pool_deas_ram" >>$conffile
echo "cloudfoundry_pool_deas_disk=$cloudfoundry_pool_deas_disk" >>$conffile
echo "cloudfoundry_pool_deas_cpu=$cloudfoundry_pool_deas_cpu" >>$conffile
echo "cloudfoundry_pool_deas_password=$cloudfoundry_pool_deas_password" >>$conffile
echo "cloudfoundry_ip_router=$cloudfoundry_ip_router" >>$conffile
echo "cloudfoundry_cloud_controller_count=$cloudfoundry_cloud_controller_count" >>$conffile
echo "cloudfoundry_stager_count=$cloudfoundry_stager_count" >>$conffile
echo "cloudfoundry_router_count=$cloudfoundry_router_count" >>$conffile
echo "cloudfoundry_deas_count=$cloudfoundry_deas_count" >>$conffile
echo "cloudfoundry_mysqlnode_count=$cloudfoundry_mysqlnode_count" >>$conffile
echo "cloudfoundry_mongodbnode_count=$cloudfoundry_mongodbnode_count" >>$conffile
echo "cloudfoundry_redisnode_count=$cloudfoundry_redisnode_count" >>$conffile
echo "cloudfoundry_rabbitnode_count=$cloudfoundry_rabbitnode_count" >>$conffile
echo "cloudfoundry_uhurufsnode_count=$cloudfoundry_uhurufsnode_count" >>$conffile
echo "cloudfoundry_postgresqlnode_count=$cloudfoundry_postgresqlnode_count" >>$conffile
echo "cloudfoundry_mssqlnode_count=$cloudfoundry_mssqlnode_count" >>$conffile
echo "cloudfoundry_windea_count=$cloudfoundry_windea_count" >>$conffile
echo "cloudfoundry_domain=$cloudfoundry_domain" >>$conffile
echo "cloudfoundry_nats_username=$cloudfoundry_nats_username" >>$conffile
echo "cloudfoundry_nats_password=$cloudfoundry_nats_password" >>$conffile
echo "cloudfoundry_ip_nats=$cloudfoundry_ip_nats" >>$conffile
echo "cloudfoundry_ccdb_password=$cloudfoundry_ccdb_password" >>$conffile
echo "cloudfoundry_ip_ccdb_postgres=$cloudfoundry_ip_ccdb_postgres" >>$conffile
echo "cloudfoundry_ccdb_dbname=$cloudfoundry_ccdb_dbname" >>$conffile
echo "cloudfoundry_ccdb_ccname=$cloudfoundry_ccdb_ccname" >>$conffile
echo "cloudfoundry_ccdb_roles_password=$cloudfoundry_ccdb_roles_password" >>$conffile
echo "cloudfoundry_srv_api_uri=$cloudfoundry_srv_api_uri" >>$conffile
echo "cloudfoundry_cc_password=$cloudfoundry_cc_password" >>$conffile
echo "cloudfoundry_cc_token=$cloudfoundry_cc_token" >>$conffile
echo "cloudfoundry_cc_staging_upload_user=$cloudfoundry_cc_staging_upload_user" >>$conffile
echo "cloudfoundry_cc_staging_upload_password=$cloudfoundry_cc_staging_upload_password" >>$conffile
echo "cloudfoundry_cc_admin=$cloudfoundry_cc_admin" >>$conffile
echo "cloudfoundry_ip_vcap_redis=$cloudfoundry_ip_vcap_redis" >>$conffile
echo "cloudfoundry_vcap_redis_password=$cloudfoundry_vcap_redis_password" >>$conffile
echo "cloudfoundry_vcap_redis_maxmemory=$cloudfoundry_vcap_redis_maxmemory" >>$conffile
echo "cloudfoundry_router_username=$cloudfoundry_router_username" >>$conffile
echo "cloudfoundry_router_password=$cloudfoundry_router_password" >>$conffile
echo "cloudfoundry_dea_maxmemory=$cloudfoundry_dea_maxmemory" >>$conffile
echo "cloudfoundry_ip_debian_nfs_server=$cloudfoundry_ip_debian_nfs_server" >>$conffile
echo "cloudfoundry_ip_hbase_master=$cloudfoundry_ip_hbase_master" >>$conffile
echo "cloudfoundry_ip_hbase_slave=$cloudfoundry_ip_hbase_slave" >>$conffile
echo "cloudfoundry_ip_opentsdb=$cloudfoundry_ip_opentsdb" >>$conffile
echo "cloudfoundry_mysql_gateway_token=$cloudfoundry_mysql_gateway_token" >>$conffile
echo "cloudfoundry_mssql_gateway_token=$cloudfoundry_mssql_gateway_token" >>$conffile
echo "cloudfoundry_uhurufs_gateway_token=$cloudfoundry_uhurufs_gateway_token" >>$conffile
echo "cloudfoundry_redis_gateway_token=$cloudfoundry_redis_gateway_token" >>$conffile
echo "cloudfoundry_mongodb_gateway_token=$cloudfoundry_mongodb_gateway_token" >>$conffile
echo "cloudfoundry_rabbit_gateway_token=$cloudfoundry_rabbit_gateway_token" >>$conffile
echo "cloudfoundry_postgresql_gateway_token=$cloudfoundry_postgresql_gateway_token" >>$conffile
echo "cloudfoundry_ip_syslog_aggregator=$cloudfoundry_ip_syslog_aggregator" >>$conffile
echo "cloudfoundry_ip_uaadb=$cloudfoundry_ip_uaadb" >>$conffile
echo "cloudfoundry_ip_simple_webui=$cloudfoundry_ip_simple_webui" >>$conffile
echo "cloudfoundry_uaadb_password=$cloudfoundry_uaadb_password" >>$conffile
echo "cloudfoundry_uaa_cc_token_secret=$cloudfoundry_uaa_cc_token_secret" >>$conffile
echo "cloudfoundry_uaa_cc_client_secret=$cloudfoundry_uaa_cc_client_secret" >>$conffile
echo "cloudfoundry_uaa_admin_client_secret=$cloudfoundry_uaa_admin_client_secret" >>$conffile
echo "cloudfoundry_uaa_login_client_secret=$cloudfoundry_uaa_login_client_secret" >>$conffile
echo "cloudfoundry_uaa_dashboard_secret=$cloudfoundry_uaa_dashboard_secret" >>$conffile
echo "cloudfoundry_dash_username=$cloudfoundry_dash_username" >>$conffile
echo "cloudfoundry_dash_password=$cloudfoundry_dash_password" >>$conffile
echo "cloudfoundry_dash_email=$cloudfoundry_dash_email" >>$conffile
echo "conf_network_micro_ip=$conf_network_micro_ip" >>$conffile
echo "conf_network_netmask=$conf_network_netmask" >>$conffile
echo "conf_resources_persistent=$conf_resources_persistent" >>$conffile
echo "conf_resources_ram=$conf_resources_ram" >>$conffile
echo "conf_resources_disk=$conf_resources_disk" >>$conffile
echo "conf_resources_cpu=$conf_resources_cpu" >>$conffile
echo "conf_network_ntp1=$conf_network_ntp1" >>$conffile
echo "conf_network_ntp2=$conf_network_ntp2" >>$conffile
echo "conf_vcenter_host=$conf_vcenter_host" >>$conffile
echo "conf_vcenter_user=$conf_vcenter_user" >>$conffile
echo "conf_vcenter_password=$conf_vcenter_password" >>$conffile
echo "conf_datacenter_name=$conf_datacenter_name" >>$conffile
echo "conf_datacenter_templatefolder=$conf_datacenter_templatefolder" >>$conffile
echo "conf_datacenter_datastorepattern=$conf_datacenter_datastorepattern" >>$conffile
echo "conf_datacenter_persistentpattern=$conf_datacenter_persistentpattern" >>$conffile
echo "conf_datacenter_mixeddatastores=$conf_datacenter_mixeddatastores" >>$conffile
echo "conf_vcenter_clustername=$conf_vcenter_clustername" >>$conffile
echo "conf_network=$conf_network" >>$conffile
echo "version_bosh_cli=$version_bosh_cli" >>$conffile
echo "version_bosh=$version_bosh" >>$conffile
echo "version_cloudfoundry=$version_cloudfoundry" >>$conffile

echo "conf_uhuru_port=$conf_uhuru_port" >>$conffile
echo "conf_uhuru_cloud_name=$conf_uhuru_cloud_name" >>$conffile
echo "conf_uhuru_domain=$conf_uhuru_domain" >>$conffile
echo "conf_uhuru_recaptcha_public_key=$conf_uhuru_recaptcha_public_key" >>$conffile
echo "conf_uhuru_recaptcha_private_key=$conf_uhuru_recaptcha_private_key" >>$conffile
echo "conf_uhuru_activation_link_secret=$conf_uhuru_activation_link_secret" >>$conffile
echo "conf_uhuru_email_from=$conf_uhuru_email_from" >>$conffile
echo "conf_uhuru_email_from_alias=$conf_uhuru_email_from_alias" >>$conffile
echo "conf_uhuru_contact_email=$conf_uhuru_contact_email" >>$conffile
echo "conf_uhuru_admin_email=$conf_uhuru_admin_email" >>$conffile
echo "conf_uhuru_admin_password=$conf_uhuru_admin_password" >>$conffile
echo "conf_uhuru_default_random_password=$conf_uhuru_default_random_password" >>$conffile

echo "cloudfoundry_mssqlnode_count=$cloudfoundry_mssqlnode_count" >>$conffile
echo "cloudfoundry_windea_count=$cloudfoundry_windea_count" >>$conffile
echo "cloudfoundry_uhuru_tunnel_count=$cloudfoundry_uhuru_tunnel_count" >>$conffile
}



function save_conf()
{
  [ ! -d $pwd/.uhuru-deployments/$deployment/deployments/micro_bosh ] && mkdir -p $pwd/.uhuru-deployments/$deployment/deployments/micro_bosh
  [ ! -d $pwd/.uhuru-deployments/$deployment/deployments/bosh ] && mkdir -p $pwd/.uhuru-deployments/$deployment/deployments/bosh
  [ ! -d $pwd/.uhuru-deployments/$deployment/deployments/cloudfoundry ] && mkdir -p $pwd/.uhuru-deployments/$deployment/deployments/cloudfoundry

  [ "$conf_datacenter_datastorepattern" == "$conf_datacenter_persistentpattern" ] && conf_datacenter_mixeddatastores="true" || conf_datacenter_mixeddatastores="false"

  write_bosh_conf $pwd/.uhuru-deployments/$deployment/deployments/bosh/bosh.yml
  write_cloudfoundry_conf $pwd/.uhuru-deployments/$deployment/deployments/cloudfoundry/cloudfoundry.yml
  write_micro_conf $pwd/.uhuru-deployments/$deployment/deployments/micro_bosh/micro_bosh.yml

  write_vars $pwd/.uhuru-deployments/$deployment/${deployment}.conf

  [ ! -d $pwd/.uhuru-deployments/$deployment/plans ] && mkdir -p $pwd/.uhuru-deployments/$deployment/plans
  cp -f $tmpdir/*_plan $pwd/.uhuru-deployments/$deployment/plans/
}
