---
wordpress:
  - screen: Network
    id: networks
    fields:
      - {name: network_name,                              label: vCenter Network,                                   type: string,
      yml_key: '["networks"][0]["subnets"][0]["cloud_properties"]["name"]',
      description: 'The name of the vCenter Network (Standard or Distributed Switch Network) that cloud VMs will be connected to. Please make sure that VMs in this network can reach the Commander VM.' }

      - {name: static_ip_range,                           label: Static IP Range,                                   type: ip_range,
      yml_key: '["networks"][0]["subnets"][0]["static"]',
      description: 'A list of IPs for cloud VMs. The "static" IPs are used for components whose IP needs to be determined prior to deployment. The routers are part of this group - their IP will be known prior to deployment, so proper DNS changes and routing can be made. An IP range looks like this: 10.0.0.100-10.0.0.120. You can specify multiple IP ranges separated by semicolons.' }

      - {name: dynamic_ip_range,                          label: Dynamic IP Range,                                  type: ip_range,
      yml_key: '["networks"][0]["subnets"][0]["reserved"]',
      description: 'A list of IP ranges used for cloud VMs. These are dynamic IPs that the Commander will assign to VMs, as they come online. Please make sure that this range does not conflict with the Static IP Range.' }

      - {name: subnet_mask,                               label: Subnet Mask,                                       type: ip,
      yml_key: '["networks"][0]["subnets"][0]["range"]',
      description: 'The subnet mask for the network.' }

      - {name: gateway,                                   label: Gateway,                                           type: ip,
      yml_key: '["networks"][0]["subnets"][0]["gateway"]',
      description: 'The gateway for the network.' }

      - {name: dns,                                       label: DNS,                                               type: ip_list,
      yml_key: '["networks"][0]["subnets"][0]["dns"]',
      description: 'A semicolon separated list of DNS servers. Please make sure that these DNS servers can translate the cloud''s domains (*.[domain] and *.tunnels.[domain]) to their proper internal IPs - or that HTTP traffic for these domains is routed to those internal IPs.' }

  - screen: Resource Pools
    id: resource_pools
    fields:

      - {name: admin_password,                            label: Administrator Password,                            type: password,
      yml_key: '["properties"]["sysadmin_password"]',
      description: 'The password of the administrator user. This password will be used for Linux "vcap" accounts. The Linux "vcap" account is part of sudoers.' }

      - {name: cpu,                                  label: Virtual CPU count,                                 type: numeric,
      yml_key: '["resource_pools"].select{|r| r["name"] == "infrastructure"}.first["cloud_properties"]["cpu"]',
      description: 'Specifies how many virtual CPUs VMs should get. Recommended value is 1.' }

      - {name: disk,                                 label: Disk,                                         type: numeric,
      yml_key: '["resource_pools"].select{|r| r["name"] == "infrastructure"}.first["cloud_properties"]["disk"]',
      description: 'Specifies how much disk space VMs should get. Recommended value is 8192 MB.' }

      - {name: ram,                                  label: Memory,                                       type: numeric,
      yml_key: '["resource_pools"].select{|r| r["name"] == "infrastructure"}.first["cloud_properties"]["ram"]',
      description: 'Specifies how much memory VMs should get. Recommended value is 2048 MB.' }

      - {name: persistent_disk,                      label: Persistent Disk,                                       type: numeric,
      yml_key: '["jobs"].select{|r| r["name"] == "mysql"}.first["persistent_disk"]',
      description: 'Specifies how much persistent disk space MYSQL should get. Recommended value is 16384 MB.' }


  - screen: Components
    id: components
    fields:

      - {name: wordpress_nodes,                                label: Wordpress Nodes,                                        type: numeric,
      yml_key: '["jobs"].select{|job| job["name"] == "wordpress"}.first["instances"]',
      description: 'Wordpress node' }

  - screen: Properties
    id: properties
    fields:

      - {name: admin_email,                               label: Administrator E-mail,                              type: string,
      yml_key: '["properties"]["wordpress"]["admin"]',
      description: 'Email address of the cloud administrator. This is going to be used to log into the cloud administration tools. ' }

      - {name: server_name,                            label: Server Domain,                            type: string,
      yml_key: '["properties"]["wordpress"]["servername"]',
      description: '' }
