pid_filename: /tmp/boshcommander.pid
bind_address: 8.8.8.8
port: 80
dev-mode: true
test_email: "spec@uhurusoftware.com" #setting used to spec smtp server

versioning:
  dir: /var/vcap/store/ucc/versions/
  blobstore_provider: swift
  blobstore_options:
    swift_provider: openstack
    container_name: test
    openstack:
      openstack_auth_url: "http://10.0.0.14:5000/v2.0"
      openstack_username: "admin"
      openstack_api_key: "password"
      openstack_tenant: "demo"

bosh_commander:
  domain: "localhost"
  skip_check_monit: true
  check_infrastructure_timeout: 10

ttyjs:
  host: 127.0.0.1
  port: 9090

nagios:
  host: 127.0.0.1
  port: 81

bosh:
  target: "https://127.0.0.1"
  #base_dir: "/home/mitza/testing/assets/vcap"
  #base_dir: "/home/vladi/tmp/testing/assets/vcap"
  base_dir: "/var/vcap"
  infrastructure: "vsphere"
  stemcells:
    linux_php_stemcell:
      name: "bosh-stemcell-php"
      version: "1.5.0.pre.3"
      system_disk: "1000"
    windows_stemcell:
      name: "uhuru-windows-2008R2"
      version: "0.9.5"
      system_disk: "2000"
    mssql_stemcell:
      name: "uhuru-windows-2008R2-sqlserver"
      version: "0.9.5"
      system_disk: "2000"
logging:
  level: debug
  file: /var/vcap/store/ucc/web-ui/uhuru_cloud_commander.log
