pid_filename: /tmp/boshcommander.pid
local_route: 10.0.21.2
port: 8000
dev-mode: true

bosh_commander:
  domain: "localhost"
  skip_check_monit: true

ttyjs:
  host: 127.0.0.1
  port: 8080

bosh:
  target: "10.0.21.22"
  #base_dir: "/home/florind/tmp/testing/assets/vcap"
  base_dir: "/home/vladi/tmp/testing/assets/vcap"
  #base_dir: "/var/vcap"
  infrastructure: "vsphere"
  stemcells:
    linux_stemcell:
      name: "bosh-stemcell"
      version: "0.6.7"
      system_disk: "1500"
    linux_php_stemcell:
      name: "bosh-stemcell-php"
      version: "0.6.4.3"
      system_disk: "1000"
    windows_stemcell:
      name: "uhuru-windows-2008R2"
      version: "0.9.3"
      system_disk: "2000"
    mssql_stemcell:
      name: "uhuru-windows-2008R2-sqlserver"
      version: "0.9.4"
      system_disk: "2000"

logging:
  level: debug
  file: /tmp/uhuru_cloud_commander.log
