--- 
pid_filename: /tmp/ucc.pid
mock_backend: true
bind_address: 10.0.0.106
port: 8080
dev-mode: true
test_email: test@uhurusoftware.com

versioning:
  dir: /tmp/vlad_versions/
  blobstore_provider: dav
  refresh_rate: 5
  blobstore_options:
    endpoint: http://roblob.uhurucloud.net:9988
    user: 'vladi'
    password: 'password1234!'

bosh_commander: 
  domain: localhost
  skip_check_monit: true
  check_infrastructure_timeout: 10
ttyjs: 
  host: 127.0.0.1
  port: 9090
nagios: 
  host: 127.0.0.1
  port: 81
bosh: 
  target: 10.0.37.37
  base_dir: /var/vcap
  infrastructure: vsphere
  stemcells: 
    linux_php_stemcell: 
      name: bosh-stemcell-php
      version: 1.5.0.pre.3
      system_disk: "1000"
    windows_stemcell: 
      name: uhuru-windows-2008R2
      version: 0.9.5
      system_disk: "2000"
    mssql_stemcell: 
      name: uhuru-windows-2008R2-sqlserver
      version: 0.9.5
      system_disk: "2000"
logging: 
  level: debug
  file: /tmp/uhuru_cloud_commander.log
