pid_filename: /tmp/boshcommander.pid
local_route: 10.0.0.3
port: 8000
dev-mode: true

bosh_commander:
  domain: "localhost"

bosh:
  target: "10.0.21.22"
  base_dir: "/home/vladi/tmp/testing/assets/vcap"
#  base_dir: "/var/vcap"
  infrastructure: "vsphere"
  stemcells:
    linux_stemcell:
      name: "bosh-stemcell"
      version: "0.6.7"
    linux_php_stemcell:
      name: "bosh-stemcell-php"
      version: "0.6.4.3"
    windows_stemcell:
      name: "uhuru-windows-2008R2"
      version: "0.9.3"
    mssql_stemcell:
      name: "uhuru-windows-2008R2-sqlserver"
      version: "0.9.4"

logging:
  level: debug
  file: /tmp/uhuru_cloud_commander.log
