---
infrastructure:
  - screen: CPI
    id: cpi
    fields:
      - {name: blobstore_sep,                             label: Blobstore Settings,                                  type: separator }

      - {name: blobstore_user,                        label: Blobstore Account,                                       type: string,
      yml_key: '["properties"]["compiled_package_cache"]["options"]["user"]',
      description: 'The account provided to you by Uhuru Software' }

      - {name: blobstore_password,                        label: Blobstore Account Password,                          type: password,
      yml_key: '["properties"]["compiled_package_cache"]["options"]["password"]',
      description: 'The password for the Uhuru blobstore account.' }

      - {name: blobstore_location,                        label: Blobstore Server,                                    type: list, items: { 'US West' : 'http://packages.uhurusoftware.com:8000', 'Europe' : 'http://packagesro.uhurusoftware.com:8000', 'US West Lab' : 'http://packages.uhurusoftware.com:9988', 'Europe Lab' : 'http://packagesro.uhurusoftware.com:9988' },
      yml_key: '["properties"]["compiled_package_cache"]["options"]["endpoint"]',
      description: 'Server used for software updates' }


      - {name: infrastructure_sep,                                label: Infrastructure Settings,                     type: separator }

      - {name: 'openstack_auth_url', yml_key: '["properties"]["openstack"]["auth_url"]',
      label: 'Identity Endpoint',
      description: 'URL of the OpenStack Identity endpoint to connect to',
      type: string,
      disable_update: true }

      - {name: 'openstack_username', yml_key: '["properties"]["openstack"]["username"]',
      label: 'Username',
      description: 'OpenStack user name',
      type: string,
      disable_update: true }

      - {name: 'openstack_api_key', yml_key: '["properties"]["openstack"]["api_key"]',
      label: 'API key',
      description: 'OpenStack API key',
      type: string,
      disable_update: true }

      - {name: 'openstack_tenant', yml_key: '["properties"]["openstack"]["tenant"]',
      label: 'Tenant Name',
      description: 'OpenStack tenant name',
      type: string,
      disable_update: true }

      - {name: 'openstack_region', yml_key: '["properties"]["openstack"]["region"]',
      label: 'Region (optional)',
      description: 'OpenStack region (optional)',
      type: string,
      disable_update: true }

      - {name: 'openstack_endpoint_type', yml_key: '["properties"]["openstack"]["endpoint_type"]',
      label: 'Endpoint Type (optional)',
      description: 'OpenStack endpoint type (optional, by default publicURL)',
      type: string,
      disable_update: true }

      - {name: 'openstack_state_timeout', yml_key: '["properties"]["openstack"]["state_timeout"]',
      label: 'Timeout (seconds)',
      description: 'Timeout (in seconds) for OpenStack resources desired state (optional, by default 300)',
      type: numeric,
      disable_update: true }

      - {name: 'openstack_stemcell_public_visibility', yml_key: '["properties"]["openstack"]["stemcell_public_visibility"]',
      label: 'Public Visibility',
      description: 'Set public visibility for stemcells (optional, false by default)',
      type: boolean,
      disable_update: true }

      - {name: 'openstack_default_key_name', yml_key: '["properties"]["openstack"]["default_key_name"]',
      label: 'VM Key Name',
      description: 'Default OpenStack keypair to use when spinning up new vms',
      type: string,
      disable_update: true }

      - {name: 'openstack_default_security_groups', yml_key: '["properties"]["openstack"]["default_security_groups"]',
      label: 'VM Security Groups',
      description: 'Default OpenStack security groups to use when spinning up new vms',
      type: csv,
      disable_update: true }

      - {name: ntp,                                       label: NTP Servers,                                         type: csv,
      yml_key: '["properties"]["ntp"]',                   disable_update: true,
      description: 'Network Time Protocol Servers. A semicolon separated list of NTP server that we use to keep time in sync across deployments.' }

      - {name: net_interface,                                       label: Network Interface,                                         type: list, items: {'127.0.0.1' : '127.0.0.1'},       disable_update: true,
      yml_key: [ '["properties"]["nats"]["address"]', '["properties"]["postgres"]["host"]', '["properties"]["director"]["address"]', '["properties"]["dns"]["address"]', '["properties"]["blobstore"]["address"]', '["properties"]["nagios"]["listen_address"]' ],
      description: 'Network interface used for configuration' }

      - {name: nagios_sep,                                label: Nagios Monitoring Settings,                        type: separator }

      - {name: nagios_warn_level,                         label: Warning Level (%),                                 type: numeric,
      yml_key: '["properties"]["nagios"]["default_warn_level"]',
      description: 'This controls the threshold (percentage) at which various metrics will be considered to be in a <b>warning</b> state. Some metrics may override this setting.'}

      - {name: nagios_critical_level,                     label: Critical Level (%),                                type: numeric,
      yml_key: '["properties"]["nagios"]["default_critical_level"]',
      description: 'This controls the threshold (percentage) at which various metrics will be considered to be in a <b>critical</b> state. Some metrics may override this setting.'}

      - {name: nagios_email_to,                           label: Send E-mail Alerts To,                             type: string,
      yml_key: '["properties"]["nagios"]["alerts"]["email_to"]',
      description: 'Nagios will send notification e-mails to the e-mail address you specify here.'}

      - {name: nagios_notification_interval,              label: Notification Interval,                             type: numeric,
      yml_key: '["properties"]["nagios"]["alerts"]["notification_interval"]',
      description: 'Nagios will keep sending notification e-mails for existing problems every X minutes. X must be greater than or equal to the default check interval (10 minutes). To only send notifications once (upon detection), set this to 0.'}

      - {name: nagios_email_sep,                          label: E-mail Settings,                                   type: separator }

      - {name: nagios_email_from,                         label: From Address,                                      type: string,
      yml_key: '["properties"]["nagios"]["email"]["from"]',
      description: 'The sender e-mail address for notification e-mail messages.'}

      - {name: nagios_email_from_alias,                   label: From Alias,                                        type: string,
      yml_key: '["properties"]["nagios"]["email"]["from_alias"]',
      description: 'A friendly sender''s alias.'}

      - {name: nagios_email_server,                       label: Server,                                            type: string,
      yml_key: '["properties"]["nagios"]["email"]["server"]',
      description: 'The SMTP server used for sending emails.'}

      - {name: nagios_email_server_port,                  label: SMTP Port,                                         type: string,
      yml_key: '["properties"]["nagios"]["email"]["port"]',
      description: 'Port for connecting to the SMTP server.'}

      - {name: nagios_email_server_user,                  label: Username,                                          type: string,
      yml_key: '["properties"]["nagios"]["email"]["user"]',
      description: 'Username for authenticating on the SMTP Server.'}

      - {name: nagios_email_server_secret,                label: Password,                                          type: password,
      yml_key: '["properties"]["nagios"]["email"]["secret"]',
      description: 'Password for authenticating on the SMTP Server.'}

      - {name: nagios_email_server_auth_method,           label: Authentication Method,                             type: list,       items: {'Plain': 'plain', 'Login': 'login', 'CRAM-MD5': 'cram_md5'},
      yml_key: '["properties"]["nagios"]["email"]["auth_method"]',
      description: 'Authentication Method used by the SMTP Server (Plain, Login or SMTP Authentication: [RFC2554]). Please consult your provider on which one of these you should use. The Commander verifies these settings, and you''ll be notified if they don''t work.'}

      - {name: nagios_email_server_enable_tls,            label: Use TLS,                                           type: boolean,
      yml_key: '["properties"]["nagios"]["email"]["enable_tls"]',
      description: 'Specifies whether the SMTP server uses TLS.'}
