---

properties:
  micro: true
  vcenter:
    address: 127.0.0.1
    user: user
    password: password
    datacenters:
      - name: uhuru_ucc
        vm_folder: uhuru_ucc_vms
        template_folder: uhuru_ucc_templates
        disk_path: uhuru_ucc_deployer
        datastore_pattern: datastore
        persistent_datastore_pattern: datastore
        allow_mixed_datastores: true
        clusters:
          - Cluster
  nats:
    user: c8329f8a7a93b60cfda14fa24a7d80db
    password: 1486cf7bd66801a070a7bc22879c85dd
    auth_timeout: 10
    ping_max_outstanding: 5
    address: 127.0.0.1
    listen_address: 0.0.0.0
    port: 4222
    no_epoll: false
    no_kqueue: true
    ping_interval: 5
    http:
      port: 9222
  redis:
    address: 127.0.0.1
    password: aba2cf9f6e9951a7cbe144a909510c33
    port: 25255
    loglevel: info
  postgres: &4644840
    password: 6489d5fd3186df63a1497bc263622329
    host: 127.0.0.1
    listen_address: 127.0.0.1
    database: bosh
    user: bosh
    port: 5432
    adapter: postgres
    connection_options:
      max_connections: 32
      pool_timeout: 10
  blobstore:
    address: 127.0.0.1
    director:
      user: director
      password: cfefdfe95a791bdbc05953360bef1f9c
    agent:
      user: agent
      password: 96a54ae31b549b3cbcd584411f0587a3
    port: 25250
    backend_port: 25251
    provider: dav
  director:
    address: 127.0.0.1
    name: micro
    port: 25555
    db: *4644840
    backend_port: 25556
    nginx:
      workers: 2
    timeout: 7200
    max_upload_size: 5000m
    encryption: false
    max_tasks: 500
    max_threads: 1
    snapshot_schedule: 0 0 7 * * * UTC
    self_snapshot_schedule: 0 0 6 * * * UTC
    auto_fix_stateful_nodes: true
  hm:
    http:
      user: hm
      password: 45a469e10219c14eb5b1eb8d24f64971
      port: 25923
    director_account:
      user: admin
      password: admin
    intervals:
      log_stats: 300
      agent_timeout: 180
      rogue_agent_alert: 180
      prune_events: 30
      poll_director: 60
      poll_grace_period: 30
      analyze_agents: 60
    loglevel: info
    email_notifications: false
    tsdb_enabled: false
    pagerduty_enabled: false
    varz_enabled: false
    cloud_watch_enabled: false
    resurrector_enabled: false
    resurrector:
      minimum_down_jobs: 5
      percent_threshold: 0.2
      time_threshold: 600
    datadog_enabled: false
  dns:
    address: 127.0.0.1
    domain_name: microbosh
    db: *4644840
    webserver:
      port: 8081
      address: 0.0.0.0
  compiled_package_cache:
    provider: s3
  ntp:
   - 0.pool.ntp.org
   - 1.pool.ntp.org
  registry:
    http:
      port: 25777
      user: user
      password: pass
    db:
      adapter: postgres
      user: bosh
      password: 6489d5fd3186df63a1497bc263622329
      host: 127.0.0.1
      port: 5432
      database: bosh_registry
      connection_options:
        max_connections: 32
        pool_timeout: 10
  openstack:
    endpoint_type: publicURL
  vcd:
    entities:
      vm_metadata_key: vcd-cf
      description: vcd-cf
  event_nats_enabled: false
  nagios:
    default_warn_level: 80
    default_critical_level: 90
    alerts:
      email_to: alerts@mycompany.org
      notification_interval: 0
    admin: nagios
    password: 39a3bdffb4eda7e184f92d9c078d397f
    director_user: nagiosuser
    director_password: c9c3214dc099c2108903f0e166844563
    email:
      from_alias: Nagios
      from: nagios@mycompany.org
      server: localhost
      port: 587
      user: user
      secret: secret
      auth_method: ":plain"
      enable_tls: true
    legacy:
      enabled: false
  compiled_package_cache:
    options:
      endpoint: http://roblob.uhurucloud.net:9988/
      user: 'vladi'
      password: 'password1234!'
