---
properties:
  micro: true
  vcenter:
    address: 127.0.0.1
    user: user
    password: password
    datacenters:
    - name: uhuru_ucc
      vm_folder: uhuru_ucc_vms
      template_folder: uhuru_ucc_templates
      disk_path: uhuru_ucc_deployer
      datastore_pattern: datastore
      persistent_datastore_pattern: datastore
      allow_mixed_datastores: true
      clusters:
      - Cluster
  nats:
    user: d635494bf03a978d34e18dec8f135932
    password: fc05e2afc575c091d5168023e0e44ab1
    auth_timeout: 10
    ping_max_outstanding: 5
    address: 127.0.0.1
    listen_address: 0.0.0.0
    port: 4222
    no_epoll: false
    no_kqueue: true
    ping_interval: 5
    http:
      port: 9222
  redis:
    address: 127.0.0.1
    password: 38af67965364350fc7a34646297f00ef
    port: 25255
    loglevel: info
  postgres: &17776380
    password: 171989697cf72f12766f27932e1c3677
    host: 127.0.0.1
    listen_address: 127.0.0.1
    database: bosh
    user: bosh
    port: 5432
    adapter: postgres
    connection_options:
      max_connections: 32
      pool_timeout: 10
  blobstore:
    address: 127.0.0.1
    director:
      user: director
      password: 2ab2f61c57203017353a32dd1a179d56
    agent:
      user: agent
      password: 429f026cbc266cb63c5e32ad8869e5f0
    port: 25250
    backend_port: 25251
    provider: dav
  director:
    address: 127.0.0.1
    name: micro
    port: 25555
    db: *17776380
    backend_port: 25556
    nginx:
      workers: 2
    timeout: 7200
    max_upload_size: 7000m
    encryption: false
    max_tasks: 500
    max_threads: 1
    auto_fix_stateful_nodes: true
    enable_snapshots: false
    proxy_timeout: 900
  hm:
    http:
      user: hm
      password: e3493b41d8f8d6c7877b7e8a251db6ea
      port: 25923
    director_account:
      user: hm_user
      password: bcf1c6f87bf63842df582f2375856918
    intervals:
      log_stats: 300
      agent_timeout: 180
      rogue_agent_alert: 180
      prune_events: 30
      poll_director: 60
      poll_grace_period: 30
      analyze_agents: 60
    loglevel: info
    email_notifications: false
    tsdb_enabled: false
    pagerduty_enabled: false
    varz_enabled: false
    cloud_watch_enabled: false
    resurrector_enabled: false
    resurrector:
      minimum_down_jobs: 5
      percent_threshold: 0.2
      time_threshold: 600
    datadog_enabled: false
  dns:
    address: 127.0.0.1
    domain_name: microbosh
    db: *17776380
    webserver:
      port: 8081
      address: 0.0.0.0
  compiled_package_cache:
    read_only: false
    provider: dav
    options:
      endpoint: http://packages.uhurusoftware.com:8000/
      user: user
      password: password
  ntp:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  registry:
    http:
      port: 25777
      user: user
      password: pass
    db:
      adapter: postgres
      user: bosh
      password: 171989697cf72f12766f27932e1c3677
      host: 127.0.0.1
      port: 5432
      database: bosh_registry
      connection_options:
        max_connections: 32
        pool_timeout: 10
  openstack:
    endpoint_type: publicURL
  vcd:
    entities:
      vm_metadata_key: vcd-cf
      description: vcd-cf
  event_nats_enabled: false
  nagios:
    listen_address: 127.0.0.1
    default_warn_level: 80
    default_critical_level: 90
    alerts:
      email_to: alerts@mycompany.org
      notification_interval: 0
    admin: nagios
    password: 3dd64de40c0222b586f6f0c1d9197cce
    director_user: hm_user
    director_password: bcf1c6f87bf63842df582f2375856918
    email:
      from_alias: Nagios
      from: nagios@mycompany.org
      server: localhost
      port: 587
      user: user
      secret: secret
      auth_method: ':plain'
      enable_tls: true
    legacy:
      enabled: false
