---
products:
  ucc:
    label: Uhuru Cloud Commander
    type: ucc
    description: Uhuru Cloud Management Tools
  uhuru-windows-2008R2:
    label: Windows Stemcell
    type: stemcell
    description: Windows 2008 R2 OS with BOSH Agent
  clouds:
    label: App Cloud
    type: software
    description: Uhuru PaaS
  cloudfoundry:
    label: AppCloud1
    type: software
    description: Uhuru PaaS