#!/bin/bash

pidfile="/var/vcap/sys/run/ttyjs.pid"

function start()
{
  echo "Starting tty.js ..."
  cd /var/vcap/store/tty.js

  BUNDLE_GEMFILE=/var/vcap/store/ucc/web-ui/Gemfile \
HOME=/root \
SHELL=/bin/bash \
TERM=xterm \
USER=root \
USERNAME=root \
PATH=/var/vcap/bosh/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin \
./bin/tty.js --config config/config.json 1>/var/vcap/store/tty.js/ttyjs.stdout.log 2>/var/vcap/store/tty.js/ttyjs.stderr.log &

  sleep 1
  pidof tty.js >$pidfile
}

function stop()
{
  [ ! -e $pidfile ] &&
    {
    echo "Can't find pid file. Are you sure tty.js is running ?"
    } ||
    {
    echo "Stopping tty.js ..."
    kill -9 `cat $pidfile`
    rm -f $pidfile
    }
}

function restart()
{
  stop
  start
}

function status()
{
  [ -e $pidfile ] &&
    {
    ps `cat $pidfile` 1>/dev/null 2>/dev/null &&
      {
      echo "tty.js appears to be running with pid `cat $pidfile` ..."
      exit 0
      } || {
      echo "tty.js is not running although there is a pid file $pidfile. You can remove it..."
      exit 0
      }
    } ||
    {
    echo "tty.js doesn't appear to be running"
    exit 0
    }
}

function help()
{
  echo "Usage:"
  echo "$0 {start|stop|restart|status}"
  exit 0
}

case $1 in
  "start") start ;;
  "stop") stop ;;
  "restart") restart ;;
  "status") status ;;
  *) help ;;
esac
exit 0
