#!/bin/bash

pidfile="/var/vcap/sys/run/ucc.pid"

function start()
{
  echo "Starting UCC ..."

  for session in $(screen -ls | grep -o '[0-9]*\.commander_screen'); do screen -S "${session}" -X quit; done

  screen -S commander_screen -d -m bash -c  "cd /var/vcap/store/ucc/web-ui/bin ; BUNDLE_GEMFILE=/var/vcap/store/ucc/web-ui/Gemfile HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/var/vcap/packages/ruby/bin /var/vcap/packages/ruby/bin/bundle exec /var/vcap/packages/ruby/bin/ruby boshcommander 1>/var/vcap/store/ucc/ucc.stdout.log 2>/var/vcap/store/ucc/ucc.stderr.log ; exit"
}


function stop()
{
    echo "Stopping UCC ..."

    for session in $(screen -ls | grep -o '[0-9]*\.commander_screen'); do screen -S "${session}" -X quit; done

  [ ! -e $pidfile ] &&
    {
    echo "Can't find pid file. Are you sure UCC is running ?"
    } ||
    {



    kill -9 `cat $pidfile`
    rm -f $pidfile
    }
}

function restart()
{
  stop
  start
}

function status()
{
  [ -e $pidfile ] &&
    {
    ps `cat $pidfile` 1>/dev/null 2>/dev/null &&
      {
      echo "UCC appears to be running with pid `cat $pidfile` ..."
      exit 0
      } || {
      echo "UCC is not running although there is a pid file $pidfile. You can remove it..."
      exit 0
      }
    } ||
    {
    echo "UCC doesn't appear to be running"
    exit 0
    }
}

function help()
{
  echo "Usage:"
  echo "$0 {start|stop|restart|status}"
  exit 0
}

case $1 in
  "start") start ;;
  "stop") stop ;;
  "restart") restart ;;
  "status") status ;;
  *) help ;;
esac
exit 0
