---
products:
  uhuru-windows-2008R2:
    label: "Windows 2008 R2 OS"
    description: "Windows 2008 R2 operating system with IIS installed."
    type: stemcell
    blobstore_id: 68976e3e7b2a2f0013738149aa7c8afe
  bosh-stemcell-php:
    label: "Ubuntu Linux 10.04 (Lucid) OS"
    description: "Minimal Ubuntu 10.04 operating system."
    type: stemcell
    blobstore_id: d0ab454500aed07141ba262900b7f783
  appcloud:
    label: "Uhuru AppCloud PaaS"
    description: "The Uhuru AppCloud - Enterprise Edition brings all the benefits of the versatile Uhuru Platform as a Service to your private network. You can run AppCloud - EE in your own datacenter or private cloud, providing complete control of security and servers without sacrificing any of the application deployment and management capabilities available to Uhuru AppCloud users in the public services."
    type: software
    blobstore_id: eb6dbf01125a02aa6d9846cae3216613
  uhuru-windows-2008R2-sqlserver:
    label: "Windows 2008 R2 OS with Microsoft SQL Server"
    description: "Windows 2008 R2 operating system with Microsoft SQL Server installed."
    type: stemcell
    blobstore_id: b3229ba8012c1a301fb3b2c453379490
