--- 
products: 
  uhuru-windows-2008R2: 
    label: Windows Stemcell
    description: Windows 2008 R2 Stemcell
    type: stemcell
    blobstore_id: 68976e3e7b2a2f0013738149aa7c8afe
  bosh-stemcell-php: 
    label: BOSH Stemcell
    description: BOSH Stemcell with PHP
    type: stemcell
    blobstore_id: d0ab454500aed07141ba262900b7f783
  appcloud: 
    label: Appcloud
    description: Uhuru App Cloud
    type: software
    blobstore_id: eb6dbf01125a02aa6d9846cae3216613
  bosh-stemcell-vsphere: 
    label: bosh-stemcell-vsphere
    description: none
    type: stemcell
    blobstore_id: 8ebf3678d8a3f9a46cc1bd09fea49016
  bosh-stemcell-php-vsphere: 
    label: bosh-stemcell-php
    description: none
    type: stemcell
    blobstore_id: c118316fad1a4f1b049c3e4945c4536b
  uhuru-windows-2008R2-sqlserver: 
    label: SqlServer Stemcell
    description: Windows 2008 R2 Stemcell with SqlServer
    type: stemcell
    blobstore_id: b3229ba8012c1a301fb3b2c453379490
