---
name: bosh
director_uuid: "DO NOT CHANGE THIS STRING"
release:
  name: uhuru-bosh
  version: 10.1-dev

networks:
- name: default
  subnets:
  - reserved:
    static:
    - 10.134.0.2 - 10.134.0.254
    range: 10.134.0.0/16
    gateway: 10.134.0.1
    dns:
    - 192.168.1.130
    - 8.8.8.8
    cloud_properties:
      name: VM Network

resource_pools:
- name: small
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  network: default
  size: 2
  cloud_properties:
    ram: 2048
    disk: 8192
    cpu: 1
- name: medium
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  network: default
  size: 2
  cloud_properties:
    ram: 4096
    disk: 16384
    cpu: 2
- name: medium_extra
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  network: default
  size: 1
  cloud_properties:
    ram: 4096
    disk: 50000
    cpu: 2
- name: large
  stemcell:
    name: bosh-stemcell
    version: 0.6.7
  network: default
  size: 0
  cloud_properties:
    ram: 8192
    disk: 32768
    cpu: 4

compilation:
  workers: 6
  network: default
  cloud_properties:
    ram: 2048
    disk: 4048
    cpu: 4

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 1
  max_errors: 1

jobs:

- name: nats
  template: nats
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.134.0.134

- name: postgres
  template: postgres
  instances: 1
  resource_pool: medium
  persistent_disk: 5000
  networks:
  - name: default
    static_ips:
    - 10.134.0.135

- name: redis
  template: redis
  instances: 1
  resource_pool: small
  persistent_disk: 5000
  networks:
  - name: default
    static_ips:
    - 10.134.0.136

- name: director
  template: director
  instances: 1
  resource_pool: medium_extra
  persistent_disk: 5000
  networks:
  - name: default
    static_ips:
    - 10.134.0.137

- name: blobstore
  template: blobstore
  instances: 1
  resource_pool: medium
  persistent_disk: 100500
  networks:
  - name: default
    default: [dns, gateway]
    static_ips:
    - 10.134.0.138
  -name: deployments

properties:
  env:
    #http_proxy: "http://<proxy>"
    #https_proxy: "http://<proxy>"
    #no_proxy: ""

  blobstore:
    address: 10.134.0.138
    port: 25251
    backend_port: 25552
    agent:
      user: agent
      password: agent
    director:
      user: director
      password: director

  networks:
    apps: default
    management: default

  nats:
    user: olCiM3B83fOB
    password: IaSmu0AeI2ky
    address: 10.134.0.134
    port: 4222

  postgres:
    user: bosh
    password: bosh
    address:  10.134.0.135
    port: 5432
    database: bosh

  redis:
    address: 10.134.0.136
    port: 25255
    password: redis

  director:
    name: bosh_director
    address: 10.134.0.137
    port: 25555

  vcenter:
    address: 192.168.1.114
    user: administrator
    password: password1234!
    datacenters:
      - name: uhuru
        vm_folder: m_bosh_vms
        template_folder: m_bosh_templates
        disk_path: m_bosh_full
        datastore_pattern: san6tb
        persistent_datastore_pattern: san6tb
        allow_mixed_datastores: true
        clusters:
        - Staging
