source :rubygems

gem "sinatra"
gem "vcap_common"
gem "vcap_logging"
gem "thin"
gem "ip"
gem "ipadmin"
gem "ipaddress"
gem "netaddr"

gem "sinatra-session"
gem "steno", "~>1.0.2"
gem "cfoundry"
gem "yajl-ruby"
gem "bosh_cli", "~> 1.0.3", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '1b33cef'
gem "uuidtools"
gem "monit_api"
gem "sequel"
gem "pg"
gem "bcrypt-ruby"
gem 'rbvmomi'
gem "rack-reverse-proxy", :require => "rack/reverse_proxy"

