source "https://rubygems.org"

gem "sinatra"
gem "vcap_common"
gem "vcap_logging"
gem "thin"
gem "ip"
gem "ipadmin"
gem "ipaddress"
gem "netaddr"

gem "sinatra-session"
gem "steno"
gem "cfoundry"
gem "yajl-ruby"
gem "bosh_cli", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '388d53aa7c443622a1b8c52be42ad5a1357aeb2c'
gem "bosh_cli_plugin_micro", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '388d53aa7c443622a1b8c52be42ad5a1357aeb2c'
gem "net-ssh-gateway", "= 1.1.0"
gem "uuidtools"
gem "sequel"
gem "pg"
gem "bcrypt-ruby"
gem 'rbvmomi'
gem 'rack-test'
gem "rack-reverse-proxy", :require => "rack/reverse_proxy"
gem "rspec", "~>2.10"
gem "rake"
gem "blobstore_client", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '388d53aa7c443622a1b8c52be42ad5a1357aeb2c'
gem "archive-tar-minitar", "~> 0.5.2"
gem "plugin_manager", "~> 1.5"

gem "crack"
gem "nokogiri", "=1.5.5"
