require 'rspec/core/rake_task'
require 'fileutils'
require 'yaml'

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __FILE__)
$:.unshift(File.expand_path("../../lib", __FILE__))

if defined?(YAML::ENGINE.yamler)
  YAML::ENGINE.yamler = RUBY_VERSION >= "2.0.0" ? "psych" : "syck"
end


require "rubygems"
require "bundler/setup"

RSpec::Core::RakeTask.new(:spec)

task :version_tests => :spec
