--- 
name: mitza
director_uuid: 5babe1a1-3727-4b85-9d22-bed352fd8914
release: 
  name: app-cloud
  version: 122.1-dev
compilation: 
  workers: 6
  reuse_compilation_vms: true
  network: default
  cloud_properties: 
    ram: 2048
    disk: 8096
    cpu: 4
update: 
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 2
networks: 
- name: default
  subnets: 
  - reserved: 
    - 10.0.0.2-10.0.5.9
    - 10.0.5.71-10.0.255.254
    static: 
    - 10.0.5.10-10.0.5.50
    range: 10.0.0.0/16
    gateway: 10.0.0.1
    dns: []

    cloud_properties: 
      name: ""
resource_pools: 
- name: windows
  network: default
  size: 1
  stemcell: 
    name: uhuru-windows-2008R2
    version: 0.9.3
  cloud_properties: 
    ram: 2048
    disk: 10000
    cpu: 4
  env: 
    windows: 
      product_key: 00000-00000-00000-00000-00000
- name: sqlserver
  network: default
  size: 0
  stemcell: 
    name: uhuru-windows-2008R2-sqlserver
    version: 0.9.4
  cloud_properties: 
    ram: 2048
    disk: 10000
    cpu: 4
  env: 
    windows: 
      product_key: 00000-00000-00000-00000-00000
- name: tiny
  network: default
  size: 6
  stemcell: 
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties: 
    ram: 300
    disk: 5000
    cpu: 1
- name: small
  network: default
  size: 3
  stemcell: 
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties: 
    ram: 512
    disk: 5000
    cpu: 1
- name: medium
  network: default
  size: 10
  stemcell: 
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties: 
    ram: 1024
    disk: 5000
    cpu: 2
- name: large
  network: default
  size: 1
  stemcell: 
    name: bosh-stemcell
    version: 0.6.7
  cloud_properties: 
    ram: 2048
    disk: 10000
    cpu: 4
- name: deas
  network: default
  size: 1
  stemcell: 
    name: bosh-stemcell-php
    version: 0.6.4.3
  cloud_properties: 
    ram: 1024
    disk: 5000
    cpu: 2
jobs: 
- name: debian_nfs_server
  template: debian_nfs_server
  instances: 1
  resource_pool: small
  persistent_disk: 50000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.10
- name: syslog_aggregator
  template: syslog_aggregator
  instances: 1
  resource_pool: medium
  persistent_disk: 1000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.11
- name: nats
  template: nats
  instances: 1
  resource_pool: small
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.12
- name: ccdb
  template: postgres
  instances: 1
  resource_pool: medium
  persistent_disk: 10000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.13
  properties: 
    db: ccdb
- name: vcap_redis
  template: vcap_redis
  instances: 1
  resource_pool: medium
  persistent_disk: 5000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.14
- name: cloud_controller
  template: cloud_controller
  instances: 1
  resource_pool: medium
  networks: 
  - name: default
- name: stager
  template: stager
  instances: 1
  resource_pool: medium
  networks: 
  - name: default
- name: router
  template: router
  instances: 1
  resource_pool: medium
  networks: 
  - name: default
    default: 
    - dns
    - gateway
    static_ips: 
    - 10.0.5.15
- name: health_manager
  template: health_manager
  instances: 1
  resource_pool: small
  networks: 
  - name: default
- name: dea
  template: dea
  instances: 1
  resource_pool: deas
  networks: 
  - name: default
- name: mysql_node
  template: mysql_node
  instances: 1
  resource_pool: medium
  persistent_disk: 75000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.16
- name: mongodb_node
  template: mongodb_node
  instances: 1
  resource_pool: medium
  persistent_disk: 75000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.17
- name: mongodb_gateway
  template: mongodb_gateway
  instances: 1
  resource_pool: tiny
  networks: 
  - name: default
- name: redis_node
  template: redis_node
  instances: 1
  resource_pool: large
  persistent_disk: 10240
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.18
- name: redis_gateway
  template: redis_gateway
  instances: 1
  resource_pool: tiny
  networks: 
  - name: default
- name: mysql_gateway
  template: mysql_gateway
  instances: 1
  resource_pool: tiny
  networks: 
  - name: default
- name: rabbit_node
  template: rabbit_node
  instances: 1
  resource_pool: medium
  persistent_disk: 10240
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.19
- name: rabbit_gateway
  template: rabbit_gateway
  instances: 1
  resource_pool: tiny
  networks: 
  - name: default
- name: postgresql_node
  template: postgresql_node
  instances: 1
  resource_pool: medium
  persistent_disk: 75000
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.20
- name: postgresql_gateway
  template: postgresql_gateway
  instances: 1
  resource_pool: tiny
  networks: 
  - name: default
- name: simple_webui
  template: simple_webui
  instances: 1
  resource_pool: tiny
  networks: 
  - name: default
    static_ips: 
    - 10.0.5.21
- name: mssql_gateway
  template: mssql_gateway
  instances: 0
  resource_pool: tiny
  networks: 
  - name: default
- name: uhurufs_gateway
  template: uhurufs_gateway
  instances: 0
  resource_pool: tiny
  networks: 
  - name: default
- name: win_dea
  template: win_dea
  instances: 0
  resource_pool: windows
  networks: 
  - name: default
- name: uhuru_tunnel
  template: uhuru_tunnel
  instances: 1
  resource_pool: windows
  networks: 
  - name: default
- name: uhurufs_node
  template: uhurufs_node
  instances: 0
  persistent_disk: 75000
  resource_pool: windows
  networks: 
  - name: default
    static_ips: []

- name: mssql_node
  template: mssql_node
  instances: 0
  persistent_disk: 75000
  resource_pool: sqlserver
  networks: 
  - name: default
    static_ips: []

properties: 
  domain: mydomain.net
  description: Cloud application platform
  support_address: http://support.mydomain.com
  env: {}

  networks: 
    apps: default
    management: default
  uhuru: 
    simple_webui: 
      port: 9191
      cloud_name: Uhuru Cloud
      cloud_admin_download_url: http://www.uhurucloud.com/tools/cloudadmin
      visual_studio_plugin_download_url: http://www.uhurucloud.com/tools/visualstudio
      vmc_url: http://docs.cloudfoundry.com/tools/vmc/installing-vmc.html
      eclipse_url: http://docs.cloudfoundry.com/tools/STS/configuring-STS.html
      signup_message: Host your web applications in minutes. We support apps written in PHP, Node.js, Ruby, Java and .NET.
      copyright_message: Copyright Uhuru Software 2012
      welcome_message: Welcome to your PAAS cloud
      color_theme: Simple
      recaptcha_public_key: <enter your recaptcha public key>
      recaptcha_private_key: <enter your recaptcha private key>
      activation_link_secret: m8oS8D1Jvw8K
      admin_email: myemail@mydomain.com
      admin_password: ""
      default_random_password: 4vahbPnVn2Bj
      logging_level: debug
      email: 
        from: uhuru@uhurusoftware.com
        from_alias: Uhuru Cloud
        server: smtp.domain.com
        port: "587"
        user: user
        secret: ""
        auth_method: ":plain"
        enable_tls: false
      contact: 
        company: Company INC.
        address: Address of company
        phone: ""
        email: myemail@mycompany.com
  win_dea: 
    filerport: 12346
    statusport: 12345
    max_memory: 6144
  uhurufs_gateway: 
    check_orphan_interval: 7200
    token: "0xfeedface"
    service_timeout: 60
    node_timeout: 30
    supported_versions: 
    - "0.9"
    version_aliases: 
      current: "0.9"
  uhurufs_node: 
    capacity: 200
    statusport: 12345
    default_version: 0.9
  mssql_gateway: 
    check_orphan_interval: 7200
    token: "0xfeedface"
    service_timeout: 60
    node_timeout: 30
    supported_versions: 
    - "2008"
    version_aliases: 
      current: "2008"
  mssql_node: 
    capacity: 200
    admin_user: sa
    admin_password: changem3!
    port: 1433
    max_db_size: 20
    max_long_query: 3
    max_long_tx: 30
    max_user_conns: 20
    default_version: 2008
    statusport: 12345
    product_key: 00000-00000-00000-00000-00000
  nats: 
    user: c9ef2d0a888a7bd412a27bd8fef85cc4
    password: 39e59c004d8db07df8462a9841f07240
    address: 10.0.5.12
    port: 4222
  ccdb: 
    user: root
    password: 383c8f76451bccb00e103c6cbcb4f627
    address: 10.0.5.13
    port: 5432
    pool_size: 10
    dbname: 2c1aae18895b17c1e52e67b7c67e797f
    databases: 
    - tag: cc
      name: 2c1aae18895b17c1e52e67b7c67e797f
    roles: 
    - tag: admin
      name: root
      password: 383c8f76451bccb00e103c6cbcb4f627
  cc: 
    srv_api_uri: api.mydomain.net
    password: c85ae6d901d9de0e8d25b2e89c76498d
    token: 6199cbe60224f3fdff3689c69f983d89
    use_nginx: true
    new_stager_percent: 100
    staging_upload_user: 6b3f411cfd673e116a4fdb2dde73e54c
    staging_upload_password: 79d2e3c1d429c12d040490eb930045cf
    allow_registration: false
    allow_external_app_uris: true
    bootstrap_users: 
    - email: myemail@mydomain.com
      password: ""
      is_admin: true
      is_hashed_password: false
    admins: 
    - myemail@mydomain.com
    default_account_capacity: 
      memory: "512"
      app_uris: 8
      services: "4"
      apps: 4
  vcap_redis: 
    address: 10.0.5.14
    port: 5454
    password: 032b80041ad837824bde7dccd2fdbf90
    maxmemory: 1024
  router: 
    client_inactivity_timeout: 120
    app_inactivity_timeout: 120
    status: 
      port: 8080
      user: a698d9b31a3f02e844d251f6e4dfe899
      password: 764eb2b4f2c79cb81f6510233bdc89c4
    redirect_parent_domain_to: www.mydomain.net
  dashboard: 
    uaa: 
      client_id: dashboard
      client_secret: secret
  dea: 
    max_memory: 6144
    maxmemory: 1024
  nfs_server: 
    address: 10.0.5.10
    network: 10.0.0.0/16
  hbase_master: 
    address: 10.134.0.155
    hbase_master: 
      port: 60000
      webui_port: 60010
      heap_size: 768
    hbase_zookeeper: 
      heap_size: 768
    hadoop_namenode: 
      port: 9000
  hbase_slave: 
    hbase_regionserver: 
      port: 60020
      heap_size: 768
    addresses: 
    - 10.134.0.156
  opentsdb: 
    address: 10.134.0.157
    port: 4242
  service_plans: 
    mysql: 
      free: 
        job_management: 
          high_water: 1400
          low_water: 100
        configuration: 
          allow_over_provisioning: false
          capacity: 100
          max_db_size: 30
          max_long_query: 20
          max_long_tx: 0
          max_clients: 20
    postgresql: 
      free: 
        job_management: 
          high_water: 1400
          low_water: 100
        configuration: 
          allow_over_provisioning: false
          capacity: 100
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 30
          max_clients: 20
    mongodb: 
      free: 
        job_management: 
          high_water: 3000
          low_water: 100
        configuration: 
          allow_over_provisioning: false
          capacity: 50
          quota_files: 4
          max_clients: 500
    redis: 
      free: 
        job_management: 
          high_water: 1400
          low_water: 100
        configuration: 
          allow_over_provisioning: false
          capacity: 50
          max_memory: 16
          max_swap: 32
          max_clients: 500
    rabbit: 
      free: 
        job_management: 
          low_water: 100
          high_water: 1400
        configuration: 
          allow_over_provisioning: false
          max_memory_factor: 0.5
          max_clients: 512
          capacity: 50
    mssql: 
      free: 
        job_management: 
          high_water: 1400
          low_water: 100
        configuration: 
          allow_over_provisioning: false
          capacity: 100
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 0
          max_clients: 20
          lifecycle: 
            enable: true
            worker_count: 1
            snapshot: 
              quota: 10
    uhurufs: 
      free: 
        job_management: 
          high_water: 1400
          low_water: 100
        configuration: 
          allow_over_provisioning: false
          capacity: 200
          max_memory: 16
          max_swap: 32
          max_clients: 500
  mysql_gateway: 
    supported_versions: 
    - "5.1"
    version_aliases: 
      current: "5.1"
    check_orphan_interval: 7200
    token: Alg82gD2mXjtyq5B
    node_timeout: 60
    service_timeout: 30
  mysql_node: 
    supported_versions: 
    - "5.1"
    default_versions: "5.1"
    production: true
    password: aaa13djkas
    op_time_limit: 50
  redis_gateway: 
    supported_versions: 
    - "2.2"
    version_aliases: 
      current: "2.2"
    token: gQ1mjpqdzhljRGju
    check_orphan_interval: 7200
    node_timeout: 60
    service_timeout: 30
  redis_node: 
    supported_versions: 
    - "2.2"
    default_versions: "2.2"
    op_time_limit: 50
  mongodb_gateway: 
    supported_versions: 
    - "1.8"
    - "2.0"
    version_aliases: 
      current: "2.0"
      deprecated: "1.8"
    check_orphan_interval: 7200
    token: ELcjgTsd7Tsfpcnz
    node_timeout: 60
    service_timeout: 30
  mongodb_node: 
    supported_versions: 
    - "1.8"
    - "2.0"
    default_version: "1.8"
    op_time_limit: 50
  rabbit_gateway: 
    supported_versions: 
    - "2.4"
    version_aliases: 
      current: "2.4"
    check_orphan_interval: 7200
    token: 9rxCftgnofi0GXZ6
    node_timeout: 60
    service_timeout: 30
  rabbit_node: 
    supported_versions: 
    - "2.4"
    default_versions: "2.4"
    op_time_limit: 50
  postgresql_gateway: 
    check_orphan_interval: 7200
    token: L01xwjdGIhHH0I4L
    supported_versions: 
    - "9.0"
    version_aliases: 
      current: "9.0"
  postgresql_node: 
    production: true
    supported_versions: 
    - "9.0"
    default_version: "9.0"
  syslog_aggregator: 
    address: 10.0.5.11
    port: 54321
  report_processor: 
    syslog_aggregator: 
      address: 10.134.0.153
      port: 54321
  stager: 
    max_staging_duration: 600
    max_active_tasks: 10
    queues: 
    - staging
  uaadb: 
    address: 10.134.0.159
    port: 2544
    roles: 
    - tag: admin
      name: root
      password: OPSLMp7nrq7g
    databases: 
    - tag: uaa
      name: uaa
  uaa: 
    cc: 
      token_secret: add79d81e6300855ebd5475d96f0ee17
      client_secret: 9f8850458daf5bd85988e6ea969e5ad9
    admin: 
      client_secret: 1645a8344e094f7fae7bba73c1c24f68
    login: 
      client_secret: 6fcd6e8126a80715398f0fec8419260a
    clients: 
      dashboard: 
        id: dashboard
        secret: 43f126ab0543cf5a98afda5db7271321
        authorized-grant-types: authorization_code,refresh_token
        scope: openid,dashboard.user
        authorities: uaa.resource,tokens.read,tokens.write
        access-token-validity: 5000
      dashborad_admin: 
        id: dashboard_admin
        secret: somesecret
        authorized-grant-types: client_credentials
        scope: uaa.none
        authorities: scim.read,scim.write,tokens.read,tokens.write,clients.read,clients.write,uaa.admin
        access-token-validity: 5000
    scim: 
      users: 
      - admin|eRihCu1V|admin@uhurucloud.net|Dash|Board|openid,dashboard.user
