source 'https://rubygems.org'

gem "blobstore_client", :git => "git@github.com:UhuruSoftware/private-bosh.git"
gem "bosh_cli", "~> 1.1868.0", :git => 'git@github.com:UhuruSoftware/private-bosh.git', :ref => '66eec1b4b64d144288e395e734ce03e64b6d87cc' 

gemspec
