source 'https://rubygems.org'

gem "blobstore_client", :git => "https://github.com/UhuruSoftware/bosh.git"
gem "bosh_cli", :git => 'https://github.com/UhuruSoftware/bosh.git', :ref => '88c3cc7b25ec5df7098edd6de3adf74ec4750680' 

gemspec
