source :rubygems

gem "sinatra"
gem "vcap_logging", :require => ['vcap/logging'], :git => 'https://github.com/cloudfoundry/common.git', :ref => 'e36886a1'
gem "sinatra-session"
gem "vcap_common",  "~> 2.0.8", :git => 'https://github.com/cloudfoundry/vcap-common.git', :ref => '7b7dd74d'
gem "steno", "~> 1.0.0"
gem "thin", "~> 1.5.0"
gem "cfoundry", "~> 0.4.0"
gem "rest-client"
gem "yajl-ruby"